export enum ProvidersEnum {
  Affiliate = 'nodejs-backend-affiliates',
  Appointment = 'nodejs-backend-appointments',
  Blog = 'nodejs-backend-blog',
  Checkout = 'nodejs-backend-checkout',
  Connect = 'nodejs-backend-connect',
  Contact = 'nodejs-backend-contacts',
  Coupon = 'nodejs-backend-coupons',
  Invoice = 'nodejs-backend-invoice',
  Message = 'nodejs-backend-message',
  Pos = 'nodejs-backend-pos',
  Product = 'nodejs-backend-products',
  Shipping = 'nodejs-backend-shipping',
  Shop = 'nodejs-backend-shop',
  Site = 'nodejs-backend-site',
  Social = 'nodejs-backend-social',
  Studio = 'nodejs-backend-studio',
  Subscription = 'nodejs-backend-billing-subscription',
  Users = 'nodejs-backend-users',
  Transactions = "nodejs-backend-transactions"
}
