export enum MediaStylesEnum {
  Vintage = 'Vintage',
  Minimalist = 'Minimalist',
  Edgy = 'Edgy',
  Trendy = 'Trendy',
  Classy = 'Classy',
  Style = 'Style',
  Boho = 'Boho',
  Aestethic = 'Aestethic',
  Inspo = 'Inspo',
  Grunge = 'Grunge',
  Retro = 'Retro',
  Casual = 'Casual',
  Hipster = 'Hipster',
  Classic = 'Classic',
  Punk = 'Punk',
  Modest = 'Modest',
  Hijab = 'Hijab',
  Vogue = 'Vogue',
  Couture = 'Couture',
  Indie = 'Indie',
  DIY = 'DIY',
  Chic = 'Chic',
  Luxury = 'Luxury',
}
