export enum PaymentOptionTypesEnum {
  SANTANDER_DE_INSTALLMENT = 'santander_installment',
  SANTANDER_DE_INVOICE = 'santander_invoice_de',
  SANTANDER_DE_POS_INVOICE = 'santander_pos_invoice_de',
  SANTANDER_DE_FACTORING = 'santander_factoring_de',
  SANTANDER_DE_POS_FACTORING = 'santander_pos_factoring_de',
  SANTANDER_DE_CCP_INSTALLMENT = 'santander_ccp_installment',
  SANTANDER_DE_POS_INSTALLMENT = 'santander_pos_installment',
  SANTANDER_NO_INSTALLMENT = 'santander_installment_no',
  SANTANDER_NO_POS_INSTALLMENT = 'santander_pos_installment_no',
  SANTANDER_NO_INVOICE = 'santander_invoice_no',
  SANTANDER_NO_POS_INVOICE = 'santander_pos_invoice_no',
  SANTANDER_DK_INSTALLMENT = 'santander_installment_dk',
  SANTANDER_DK_POS_INSTALLMENT = 'santander_pos_installment_dk',
  SANTANDER_SE_INSTALLMENT = 'santander_installment_se',
  SANTANDER_SE_POS_INSTALLMENT = 'santander_pos_installment_se',
  INVOICE = 'invoice',
  CASH = 'cash',
  SOFORT = 'sofort',
  PAYMILL_CREDIT_CARD = 'paymill_creditcard',
  PAYMILL_DIRECT_DEBIT = 'paymill_directdebit',
  PAYPAL = 'paypal',
  STRIPE_CREDIT_CARD = 'stripe',
  STRIPE_DIRECT_DEBIT = 'stripe_directdebit',
  PAYEX_FAKTURA = 'payex_faktura',
  PAYEX_CREDIT_CARD = 'payex_creditcard',
  INSTANT_PAYMENT = 'instant_payment',
}
