export enum ProvidersEnum {
  Users = 'nodejs-backend-users',
  Mailer = 'nodejs-backend-mailer',
  Shipping = 'nodejs-backend-shipping',
  ThirdParty = 'nodejs-backend-third-party',
  CheckoutPhp = 'backend-checkout',
  PaymentPayex = 'backend-payment-options-payex-rpc',
  PaymentPaypal = 'backend-payment-options-paypal-rpc',
  PaymentSantanderFactoringDe = 'backend-payment-options-santander-de-fact-rpc',
  PaymentSantanderInvoiceDe = 'backend-payment-options-santander-de-invoice-rpc',
  PaymentSantanderDe = 'backend-payment-options-santander-de-rpc',
  PaymentSantanderDk = 'backend-payment-options-santander-dk-rpc',
  PaymentSantanderNo = 'backend-payment-options-santander-no-rpc',
  PaymentSantanderSe = 'backend-payment-options-santander-se-rpc',
  PaymentSofort = 'backend-payment-options-sofort-rpc',
  PaymentStripe = 'backend-payment-options-stripe-rpc',
  PaymentStub = 'backend-payment-options-stub-proxy',
  PaymentWire = 'backend-payment-options-wiretransfer-rpc',
}
