export * from './composite.strategy';
export * from './crop.strategy';
export * from './resize.strategy';
export * from './print.strategy';
export * from './mask.strategy';
export * from './flip.strategy';
export * from './rotate.strategy';
export * from './greyscale.strategy';
export * from './fade.strategy';
