export enum ChatAppEnum {
  Ads = 'ads',
  Appointments = 'appointments',
  Affiliates = 'affiliates',
  Blog = 'blog',
  Checkout = 'checkout',
  CommerceOS = 'commerceos',
  Connect = 'connect',
  Contacts = 'contacts',
  Coupons = 'coupons',
  Mail = 'mail',
  Message = 'message',
  Pos = 'pos',
  Products = 'products',
  Shipping = 'shipping',
  Shop = 'shop',
  Site = 'site',
  Studio = 'studio',
  Social = 'social',
  Subscriptions = 'subscriptions',
  Statistics = 'statistics',
  Settings = 'settings',
  Transactions = 'transactions',
  Invoice = 'invoice',  
}
