export enum AppliedToEnum {
  ALL_PRODUCTS = 'ALL_PRODUCTS',
  SPECIFIC_CATEGORIES = 'SPECIFIC_CATEGORIES',
  SPECIFIC_PRODUCTS = 'SPECIFIC_PRODUCTS',
}

export enum SubscriberEligibilityEnum {
  EVERYONE = 'EVERYONE',
  SPECIFIC_GROUPS_OF_SUBSCRIBERS = 'SPECIFIC_GROUPS_OF_SUBSCRIBERS',
  SPECIFIC_SUBSCRIBERS = 'SPECIFIC_SUBSCRIBERS',
}
