export interface BulkSetupCsvRawRowInterface {
  'First Name': string;
  'Last Name': string;
  'Email': string;
  'Company': string;
  'Logo': string;
  'Language Code': string;
  'Country Code': string;
  'City': string;
  'Street': string;
  'Zip': string;
  'Phone': string;
  'Industry': string;
  'Product': string;
  'Bank Name': string;
  'Bank Country Code': string;
  'Bank City': string;
  'Bank Owner': string;
  'Bank BIC': string;
  'Bank IBAN': string;
  'Tax Register Number': string;
  'Tax Id': string;
  'Tax Number': string;
  'Tax Turnover Act': string;
  'Contact Emails': string;
  'Theme': string;
  'Wallpaper': string;
  'Pos App': string;
  'Shop App': string;
  'Transactions App': string;
  'Products App': string;
  'Shipping App': string;
  'Checkout Logo': string;
  'Checkout Styles': string;
  'Checkout Preset': string;
  'Connect Payment': string;
  'Connect Communication': string;
  'Connect Shipping': string;
  'Connect Shopsystems': string;
  'Connect Products': string;
  'Onboarding Name': string;
  'Template': string;
}
