export enum CheckoutPaymentStatusEnum {
  STATUS_NEW = 'STATUS_NEW',
  STATUS_IN_PROCESS = 'STATUS_IN_PROCESS',
  STATUS_ACCEPTED = 'STATUS_ACCEPTED',
  STATUS_PAID = 'STATUS_PAID',
  STATUS_DECLINED = 'STATUS_DECLINED',
  STATUS_REFUNDED = 'STATUS_REFUNDED',
  STATUS_FAILED = 'STATUS_FAILED',
  STATUS_CANCELLED = 'STATUS_CANCELLED',
}
