export const SettlementReportFieldsMapping: Map<string, string> = new Map<string, string>(
  [
    ['payever Payment ID', 'transaction_id'],
    ['Merchant Order ID', 'order_id'],
    ['PSP Reference ID', 'psp_reference_id'],
    ['Bank Reference ID', 'bank_reference_id'],
    ['Initiation Date', 'initiation_date'],
    ['Business Name', 'business_name'],
    ['Business UUID', 'business_id'],
    ['Customer Email', 'customer_email'],
    ['Customer Name', 'customer_name'],
    ['Transaction Credit/Debit', 'transaction_credit_debit'],
    ['Operation Type', 'operation_type'],
    ['Execution Date', 'execution_date'],
    ['Gross Amount', 'gross_amount'],
    ['Net Amount', 'net_amount'],
    ['Payment Fee Credit/Debit', 'payment_fee_credit_debit'],
    ['Payment Fee', 'payment_fee'],
    ['Transaction Fee', 'transaction_fee'],
    ['Currency', 'currency'],
    ['Billing Country', 'billing_country'],
    ['Billing City', 'billing_city'],
    ['Billing Street', 'billing_street'],
    ['Shipping Country', 'shipping_country'],
    ['Shipping City', 'shipping_city'],
    ['Shipping Street', 'shipping_street'],
  ],
);
