{{ $chartName := .Chart.Name }}
{{ $values := .Values }}
{{ $appName := $chartName }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ $values.namespace }}

  labels:
    app: {{ $appName }}
    tier: nodejs
    type: http

  annotations:
    "werf.io/set-replicas-only-on-creation": "true"
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'

spec:
  replicas: {{ $values.replicas.http.min }}

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ $appName }}

  template:
    metadata:
      labels:
        app: {{ $appName }}
        tier: nodejs
        type: http

      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'

    spec:
      priorityClassName: {{ $values.priorityClass }}
      imagePullSecrets:
        - name: {{ $values.image.pullSecretName }}

      terminationGracePeriodSeconds: 60

      containers:
        - name: node
          image: {{ $values.image.nodejs }}
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "/payever/deploy/deploy.sh" ]

          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10; pkill npm"]

          ports:
            - containerPort: {{ $values.service.containerPort }}
              protocol: TCP
              name: http

          livenessProbe:
            httpGet:
              path: /api/status
              port: {{ $values.service.statusPort }}
            initialDelaySeconds: 150
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/status
              port: {{ $values.service.statusPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 15

          resources:
{{ if eq .Values.deploy.env "test" }}
{{ toYaml $values.test.resources | indent 12 }}
{{ else if eq .Values.deploy.env "stage" }}
{{ toYaml $values.stage.resources | indent 12 }}
{{ else }}
{{ toYaml $values.live.resources | indent 12 }}
{{ end }}

          envFrom:
            - configMapRef:
                name: {{ $chartName }}
            - configMapRef:
                name: micro-url-map
            - secretRef:
                name: {{ $chartName }}

          env:
            - name: KUBERNETES_DEPLOYED
              value: "{{ now }}"
