const translations: { [k: string]: string } = {
  BRANCHE_ADDITIVE_PRODUCTS: 'Additive Manufacturing Products',
  BRANCHE_ADHESIVES: 'Tapes, Adhesives & Sealants',
  BRANCHE_ART_CRAFT: 'Arts & Crafts',
  BRANCHE_AUTOMOTIVE: 'Automotive',
  BRANCHE_BABY: 'Baby',
  BRANCHE_BAR: 'Bar',
  BRANCHE_BED_BRAKFAST: 'Bed & Breakfast',
  BRANCHE_BOOKS: 'Books',
  BRANCHE_CAFE: 'Cafe',
  BRANCHE_CARE: 'Beauty & Personal Care',
  BRANCHE_CAR_REPAIR: 'Car Repair',
  BRANCHE_CLUB: 'Club',
  BRANCHE_COMPUTER: 'Computers',
  BRANCHE_COMPUTER_ELECTRONIC: 'Computers & Electronics',
  BRANCHE_CONSULTING: 'Consulting',
  BRANCHE_CUTTING_TOOLS: 'Cutting Tools',
  BRANCHE_DENTAL_SUPPLIES: 'Professional Dental Supplies',
  BRANCHE_DIGITAL_GOODS: 'Digital Goods',
  BRANCHE_DIGITAL_MUSIC: 'Digital Music',
  BRANCHE_DIGITAL_VIDEOS: 'Digital Videos',
  BRANCHE_DOOR_PRODUTS: 'Commercial Door Products',
  BRANCHE_ELECTRICAL: 'Industrial Electrical',
  BRANCHE_ELECTRONICS: 'Electronics',
  BRANCHE_EROTIC: 'Erotic',
  BRANCHE_FASHION: 'Fashion',
  BRANCHE_FASTENERS: 'Fasteners',
  BRANCHE_FILTRATION: 'Filtration',
  BRANCHE_FINISHING_PRODUTS: 'Abrasive & Finishing Products',
  BRANCHE_FOOD_SUPPLIES: 'Food Service Equipment & Supplies',
  BRANCHE_FOOD_TRACK: 'Food Truck',
  BRANCHE_GAMES: 'Games',
  BRANCHE_GESUNDEIT_PFLEGE: 'Healthcare',
  BRANCHE_HAIR_STYLIST: 'Hair Stylist',
  BRANCHE_HAND_TOOLS: 'Industrial Power & Hand Tools',
  BRANCHE_HARDWARE: 'Industrial Hardware',
  BRANCHE_HAUSHALTSGARATE_TECHNIK: 'Appliances',
  BRANCHE_HEALTH: 'Occupational Health & Safety Products',
  BRANCHE_HEALTH_HOUSEHOLD: 'Health & Household',
  BRANCHE_HOME_KITCHEN: 'Home & Kitchen',
  BRANCHE_HOTEL: 'Hotel',
  BRANCHE_JANITORIAL_SUPPLIES: 'Janitorial & Sanitation Supplies',
  BRANCHE_LOCKSMITH: 'Locksmith',
  BRANCHE_LUGGAGE: 'Luggage',
  BRANCHE_MATERIAL_HANDLINGS: 'Material Handling Products',
  BRANCHE_MEASURE: 'Test, Measure & Inspect',
  BRANCHE_MEDICAL_SUPPLIES: 'Professional Medical Supplies',
  BRANCHE_MODE_TEXTILIEN: 'Clothing',
  BRANCHE_MOTEL: 'Motel',
  BRANCHE_MUSIC: 'Music, CDs & Vinyl',
  BRANCHE_MUSIK: 'Music',
  BRANCHE_NAIL_STUDIO: 'Nail Studio',
  BRANCHE_NOBLE_ACCESSORIES: 'Furniture',
  BRANCHE_OTHER: 'Others',
  BRANCHE_PET_SUPPLIES: 'Pet Supplies',
  BRANCHE_PNEUMATICS: 'Hydraulics, Pneumatics & Plumbing',
  BRANCHE_POWER_TRANSMISSION: 'Power Transmission Products',
  BRANCHE_RAW_MATERIALS: 'Raw Materials',
  BRANCHE_RESTAURANT: 'Restaurant',
  BRANCHE_RETAIL_STORE: 'Retail Store Fixtures & Equipment',
  BRANCHE_ROBOTICS: 'Robotics',
  BRANCHE_SCIENCE_EDUCATION: 'Science Education',
  BRANCHE_SCIENCE_PRODUTS: 'Lab & Scientific Products',
  BRANCHE_SHIPPING_SUPPLIES: 'Packaging & Shipping Supplies',
  BRANCHE_SOFTWARE: 'Software',
  BRANCHE_SONSTIGES: 'Other',
  BRANCHE_SPIELWAREN: 'Toys',
  BRANCHE_SPORTS: 'Sports & Outdoors',
  BRANCHE_SUPERMARKET: 'Supermarket',
  BRANCHE_TOOLS: 'Tools & Home Improvement',
  BRANCHE_TOURISM: 'Tourism',
  BRANCHE_TOYS: 'Toys & Games',
  BRANCHE_TV: 'Movies & TV',
  BRANCHE_UHREN_SCHMUCK: 'Jewelry',
  BRANCHE_VIDEO_GAMES: 'Video Games',

  BUSINESS_PRODUCT_DRINKS: 'Drinks',
  BUSINESS_PRODUCT_FOOD: 'Food',
  BUSINESS_PRODUCT_GIDITAL_GOODS: 'Digital goods',
  BUSINESS_PRODUCT_MEALS: 'Meals',
  BUSINESS_PRODUCT_OTHERS: 'Others',
  BUSINESS_PRODUCT_OVERNIGHT_STAY: 'Overnight stay',
  BUSINESS_PRODUCT_RETAIL_B2B: 'Physical goods for business customers (Retail B2B)',
  BUSINESS_PRODUCT_RETAIL_B2C: 'Physical goods for private customers (Retail B2C)',
  BUSINESS_PRODUCT_SERVICES: 'Services',
};

export function translate(value: string): string {
  return translations.hasOwnProperty(value) ? translations[value] : value;
}
