import { ApiCallAddressInterface } from './api-call-address.interface';
import { ApiCallCartItemInterface } from './api-call-cart-item.interface';
import { TwoFactorTypeEnum, VerifyTypeEnum } from '../../../legacy-api/enum';
import { ApiCallSellerInterface } from './api-call-seller.interface';
import { ApiCallMessageInterface } from './api-call-message.interface';
import { ApiCallCompanyInterface } from './api-call-company.interface';
import { ApiCallShippingOptionInterface } from './api-call-shipping-option.interface';
import { ApiCallSplitInterface } from './api-call-split.interface';
import { ApiCallFooterUrlsInterface } from './api-call-footer-urls.interface';
import { CustomerTypeEnum } from '../../enum';

export interface ApiCallInterface extends ApiCallAddressInterface {
  businessId: string;
  payment_issuer?: string;
  payment_method?: string;
  original_mapped_payment_method?: string;
  channel: string;
  channel_type?: string;
  channel_source?: string;
  channel_set_id: number | string;
  amount: number;
  order_id?: string;
  currency: string;
  flowId?: string;
  fee?: number;
  down_payment?: number;
  cart?: ApiCallCartItemInterface[] | string;
  social_security_number?: string;
  birthdate?: Date;
  phone?: string;
  email?: string;
  success_url?: string;
  pending_url?: string;
  failure_url?: string;
  cancel_url?: string;
  notice_url?: string;
  customer_redirect_url?: string;
  x_frame_host?: string;
  plugin_version?: string;
  variant_id?: string;
  original_mapped_variant_id?: string;
  allow_cart_step?: boolean;
  use_inventory?: boolean;
  expires_at?: Date;
  extra?: any;
  client_id?: string;
  execution_time?: string;
  shipping_address?: ApiCallAddressInterface;
  locale?: string;
  verify_type?: VerifyTypeEnum;
  verify_two_factor?: TwoFactorTypeEnum;
  two_factor_triggered?: boolean;
  seller?: ApiCallSellerInterface;
  reusable?: boolean;
  message?: ApiCallMessageInterface;
  skip_handle_payment_fee?: boolean;

  organization_name?: string;
  street_name?: string;
  house_extension?: string;
  reference_extra?: string;
  purchase_country?: string;
  customer_type?: CustomerTypeEnum;
  customer_gender?: string;
  company?: ApiCallCompanyInterface;
  shipping_option?: ApiCallShippingOptionInterface;
  splits?: ApiCallSplitInterface[];
  allow_separate_shipping_address?: boolean;
  allow_customer_types?: CustomerTypeEnum[];
  allow_payment_methods?: string[];
  allow_billing_step?: boolean;
  allow_shipping_step?: boolean;
  use_styles?: boolean;
  use_default_variant?: boolean;
  use_iframe?: boolean;
  salutation_mandatory?: boolean;
  phone_mandatory?: boolean;
  birthdate_mandatory?: boolean;
  test_mode?: boolean;
  api_version?: string;
  order_ref?: string;
  original_cart?: any;
  hide_logo?: boolean;
  hide_imprint?: boolean;
  auto_capture_enabled?: boolean;
  auto_capture_date?: Date;
  footer_urls?: ApiCallFooterUrlsInterface;
  payment_link_id?: string;
  disable_validation?: boolean;
}
