import { FilterFieldMapping } from '../../common/helpers';
import { ElasticProductRelationsEnum } from './elastic-product-relations.enum';

export enum ProductFilterFieldEnum {
  Album = 'album',
  Id = 'id',
  Name = 'name',
  Condition = 'condition',
  Price = 'price',
  Brand = 'brand',
  SalePrice = 'salePrice',
  Channel = 'channel',
  MarketplaceName = 'marketplace_name',
  MarketplaceType = 'marketplace_type',
  MarketplaceId = 'marketplace_id',
  Category = 'category',
  CategoryId = 'category.id',
  VariantTitle = 'variant_title',
  VariantName = 'variant_name',
  VariantType = 'variant_type',
  VariantValue = 'variant_value',
  VariantPrice = 'variant_price',
  VariantOptionsValue = 'variants_options_value',
  Sku = 'sku',
  Attributes = 'attributes',
  AttributeName = 'attributes.name',
  AttributeValue = 'attributes.value',
  Variant = 'variant',
  Categories = 'categories',
  CategoriesTitle = 'categories.title',
  ChannelSetCategoriesTitle = 'channelSetCategories.title',
  CategoriesSlug = 'categories.slug',
  CategoriesId = 'categories.id',
  ParentProduct = 'parentProduct',
  Apps = 'apps',
  Collections = 'collections',
  Slug = 'slug',
  Title = 'title',
  Type = 'type',
  Description = 'description',
  OptionValue = 'options.value',
  CollectionsName = 'collections.name',
  CollectionsDescription = 'collections.description',
  AttributesName = 'attributes.name',
  AttributesValue = 'attributes.value',
  CategoryTitle = 'category.title',
  CategoryName = 'category.name',
  Barcode = 'barcode',
}

/* tslint:disable: object-literal-sort-keys  */
export const ProductFilterFieldsTranslation: any = {
  Id: 'renderer.grid-filter._id',
  Album: 'renderer.grid-filter.album',
  Apps: 'renderer.grid-filter.apps',
  Name: 'renderer.grid-filter.title',
  Condition: 'renderer.grid-filter.condition',
  Price: 'renderer.grid-filter.price',
  Brand: 'renderer.grid-filter.brand',
  SalePrice: 'renderer.grid-filter.salePrice',
  Channel: 'renderer.grid-filter.channelSets.type',
  Category: 'renderer.grid-filter.categories.title',
  CategoryId: 'renderer.grid-filter.category',
  MarketplaceName: 'renderer.grid-filter.marketplaces.name',
  MarketplaceType: 'renderer.grid-filter.marketplaces.type',
  MarketplaceId: 'renderer.grid-filter.marketplaces._id',
  VariantTitle: 'renderer.grid-filter.variants.title',
  VariantName: 'renderer.grid-filter.variants.options.name',
  VariantType: 'renderer.grid-filter.variants.options.type',
  VariantValue: 'renderer.grid-filter.variants.options.value',
  VariantPrice: 'renderer.grid-filter.variants.price',
  VariantOptionsValue: 'renderer.grid-filter.variants.options.value',
  Sku: 'renderer.grid-filter.sku',
  Attributes: 'renderer.grid-filter.attributes',
  Variant: 'renderer.grid-filter.variant',
  AttributeName: 'renderer.grid-filter.attributes.name',
  AttributeValue: 'renderer.grid-filter.attributes.value',
  Categories: 'renderer.grid-filter.categories',
  CategoriesTitle: 'renderer.grid-filter.categories.title',
  ChannelSetCategoriesTitle: 'renderer.grid-filter.channelSetCategories.title',
  CategoriesSlug: 'renderer.grid-filter.categories.slug',
  CategoriesId: 'renderer.grid-filter.categories._id',
  ParentProduct: `renderer.grid-filter.${ElasticProductRelationsEnum.parentProduct}`,
  Collections: 'renderer.grid-filter.collections',
  Slug: 'renderer.grid-filter.slug',
  Title: 'renderer.grid-filter.title',
  Type: 'renderer.grid-filter.type',
  Description: 'renderer.grid-filter.description',
};

export const ProductFilterFieldsMapping: FilterFieldMapping<ProductFilterFieldEnum> = {
  [ProductFilterFieldEnum.Id]: '_id',
  [ProductFilterFieldEnum.Album]: 'album',
  [ProductFilterFieldEnum.Apps]: 'apps',
  [ProductFilterFieldEnum.Name]: 'title',
  [ProductFilterFieldEnum.Condition]: 'condition',
  [ProductFilterFieldEnum.Price]: 'price',
  [ProductFilterFieldEnum.Brand]: 'brand',
  [ProductFilterFieldEnum.SalePrice]: 'salePrice',
  [ProductFilterFieldEnum.Channel]: 'channelSets.type',
  [ProductFilterFieldEnum.Category]: 'categories.title',
  [ProductFilterFieldEnum.CategoryId]: 'category',
  [ProductFilterFieldEnum.MarketplaceName]: 'marketplaces.name',
  [ProductFilterFieldEnum.MarketplaceType]: 'marketplaces.type',
  [ProductFilterFieldEnum.MarketplaceId]: 'marketplaces._id',
  [ProductFilterFieldEnum.VariantTitle]: 'variants.title',
  [ProductFilterFieldEnum.VariantName]: 'variants.options.name',
  [ProductFilterFieldEnum.VariantType]: 'variants.options.type',
  [ProductFilterFieldEnum.VariantValue]: 'variants.options.value',
  [ProductFilterFieldEnum.VariantPrice]: 'variants.price',
  [ProductFilterFieldEnum.VariantOptionsValue]: 'variants.options.value',
  [ProductFilterFieldEnum.Sku]: 'sku',
  [ProductFilterFieldEnum.Attributes]: 'attributes',
  [ProductFilterFieldEnum.Variant]: 'variant',
  [ProductFilterFieldEnum.AttributeName]: 'attributes.name',
  [ProductFilterFieldEnum.AttributeValue]: 'attributes.value',
  [ProductFilterFieldEnum.Categories]: 'categories',
  [ProductFilterFieldEnum.CategoriesTitle]: 'categories.title',
  [ProductFilterFieldEnum.ChannelSetCategoriesTitle]: 'channelSetCategories.title',
  [ProductFilterFieldEnum.CategoriesSlug]: 'categories.slug',
  [ProductFilterFieldEnum.CategoriesId]: 'categories._id',
  [ProductFilterFieldEnum.ParentProduct]: ElasticProductRelationsEnum.parentProduct,
  [ProductFilterFieldEnum.Collections]: 'collections',
  [ProductFilterFieldEnum.Slug]: 'slug',
  [ProductFilterFieldEnum.Title]: 'title',
  [ProductFilterFieldEnum.Type]: 'type',
  [ProductFilterFieldEnum.Description]: 'description',
  [ProductFilterFieldEnum.OptionValue]: 'options.value',
  [ProductFilterFieldEnum.CollectionsName]: 'collections.name',
  [ProductFilterFieldEnum.CollectionsDescription]: 'collections.description',
  [ProductFilterFieldEnum.AttributesName]: 'attributes.name',
  [ProductFilterFieldEnum.AttributesValue]: 'attributes.value',
  [ProductFilterFieldEnum.CategoryTitle]: 'category.title',
  [ProductFilterFieldEnum.CategoryName]: 'category.name',
  [ProductFilterFieldEnum.Barcode]: 'barcode',
};
