export enum AppEnum { 
  Coupon = 'coupon',
  Checkout = 'checkout',
  Contact = 'contact',
  Blog = 'blog',
  Appointment = 'appointment',
  Invoice = 'invoice',
  Message = 'message',
  Pos = 'pos',
  Businesses = 'businesses',
  Users = 'users',
  Product = 'product',
  Transactions = 'transactions',
  Site = 'site',
  Shop = 'shop',
  Shipping = 'shipping',
  Subscriptions = 'subscriptions',
  Affiliate = 'affiliate',
  Connect = 'connect',
  Social = 'social',
  Studio = 'studio',
}
