include:
  - project: "infra/ci-config"
    ref: "master"
    file: '/nodejs-backend/message.yml'

Build stage:
  extends: .Build to stage
  rules:
    - if: "$RUN_ML_JOB"
      when: never
    - if: '$IN_ENVIRONMENT && $IN_ENVIRONMENT != "test"'
      when: never
    - if: '$IN_PIPELINE_TYPE && $IN_PIPELINE_TYPE == "qa"'
      when: on_success
    - if: '$IN_PIPELINE_TYPE && $IN_PIPELINE_TYPE != "deploy"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $PROJ_MASTER_BRANCH_NAME'
      when: on_success
    - if: "$CI_COMMIT_BRANCH"
      when: on_success
    - if: "$UPSTREAM_ENV"
      when: never

Deploy to stage:
  extends: .Deploy to stage
  rules:
    - if: "$RUN_ML_JOB"
      when: never
    - if: $RUN_MIGRATIONS
      when: never
    - if: '$IN_PIPELINE_TYPE == "test" && $CI_COMMIT_BRANCH == $IN_MASTER_BRANCH'
      when: never
    - if: '$IN_ENVIRONMENT && $IN_ENVIRONMENT != "test"'
      when: never
    - if: '$IN_PIPELINE_TYPE && $IN_PIPELINE_TYPE != "deploy"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $PROJ_MASTER_BRANCH_NAME'
      when: on_success
    - if: '$CI_COMMIT_BRANCH'
      when: manual
