/* eslint-disable @typescript-eslint/tslint/config */
import { Schema } from 'mongoose';
import { v4 as uuid } from 'uuid';

export const PaymentLinksSchema: Schema = new Schema(
  {
    _id: { type: String, default: uuid },
    allow_cart_step: { required: false, type: String },
    amount: { required: false, type: Number },
    reference: { required: false, type: String },
    birthdate: Date,
    business_id: { required: true, type: String },
    cancel_url: { required: false, type: String },
    channel: { required: false, type: String },
    channel_set_id: { required: false, type: String },
    channel_source: { required: false, type: String },
    channel_type: { required: false, type: String },
    client_ip: { required: false, type: String },
    currency: { type: String },
    customer_redirect_url: { required: false, type: String },
    delivery_fee: { required: false, type: Number },
    down_payment: { required: false, type: Number },
    email: { required: false, type: String },
    expires_at: { required: false, type: Date },
    extra: { required: false, type: Schema.Types.Mixed },
    failure_url: { required: false, type: String },
    fee: { required: false, type: Number },
    first_name: { required: false, type: String },
    is_deleted: { required: false, type: Boolean, default: false },
    is_active: { required: false, type: Boolean, default: true },
    creator: { required: false, type: String, default: true },
    last_name: { required: false, type: String },
    link_message: { required: false, type: Schema.Types.Mixed },
    locale: { required: false, type: String },
    notice_url: { required: false, type: String },
    order_id: { type: String },
    payment_data: { required: false, type: Schema.Types.Mixed },
    payment_issuer: { required: false, type: String },
    payment_method: { required: false, type: String },
    pending_url: { required: false, type: String },
    phone: { required: false, type: String },
    plugin_version: { required: false, type: String },
    privacy: { required: false, type: Boolean },
    reusable: { default: false, required: false, type: Boolean },
    salutation: { required: false, type: String },
    seller: { required: false, type: Schema.Types.Mixed },
    street: { required: false, type: String },
    street_number: { required: false, type: String },
    zip: { required: false, type: String },
    region: { required: false, type: String },
    city: { required: false, type: String },
    country: { required: false, type: String },
    address_line_2: { required: false, type: String },
    organization_name: { required: false, type: String },
    street_name: { required: false, type: String },
    house_extension: { required: false, type: String },
    shipping_address: { required: false, type: Schema.Types.Mixed },
    success_url: { required: false, type: String },
    use_inventory: { required: false, type: Boolean },
    variant_id: { required: false, type: String },
    verify: { required: false, type: Schema.Types.Mixed },
    x_frame_host: { required: false, type: String },

    reference_extra: { required: false, type: String },
    purchase_country: { required: false, type: String },
    customer_type: { required: false, type: String },
    customer_gender: { required: false, type: String },
    company: { required: false, type: Schema.Types.Mixed },
    shipping_option: { required: false, type: Schema.Types.Mixed },
    splits: { required: false, type: Schema.Types.Mixed },
    allow_separate_shipping_address: { required: false, type: Boolean },
    allow_customer_types: { required: false, type: Schema.Types.Mixed },
    allow_payment_methods: { required: false, type: Schema.Types.Mixed },
    allow_billing_step: { required: false, type: Boolean },
    allow_shipping_step: { required: false, type: Boolean },
    use_styles: { required: false, type: Boolean },
    use_default_variant: { required: false, type: Boolean },
    use_iframe: { required: false, type: Boolean },
    salutation_mandatory: { required: false, type: Boolean },
    phone_mandatory: { required: false, type: Boolean },
    birthdate_mandatory: { required: false, type: Boolean },
    test_mode: { required: false, type: Boolean },
    order_ref: { required: false, type: String },
    original_cart: { required: false, type: Schema.Types.Mixed },
    payment_id: { required: false, type: String },
    api_call_id: { required: false, type: String },

    transactions_count: { required: false, type: Number, default: 0 },
    views_count: { required: false, type: Number, default: 0 },
  },
  {
    timestamps: {
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  }
)
  .index({ created_at: -1 })
  .index({ business_id: 1 })
  .index({ is_deleted: 1 });

