/* eslint-disable @typescript-eslint/tslint/config */
import { PaymentMethodInterface } from '../interfaces';

const THUMBNAILS_BASE_URL: string = 'https://payeverproduction.blob.core.windows.net/miscellaneous/';
const PaymentMethodsThumbnails: { [key: string]: string } = {
  PAYEX: THUMBNAILS_BASE_URL + '335a87e0-f43c-4d4c-9aa1-9f525c4cc7f9-PAYEX.png',
  PAYPAL: THUMBNAILS_BASE_URL + '4a6223a8-cb31-4fcc-b89f-fa93e7512be1-PAYPAL.png',
  SANTANDER: THUMBNAILS_BASE_URL + '2e551b84-c162-4963-97e6-af960f24d3f3-SANTANDER.png',
  SOFORT: THUMBNAILS_BASE_URL + '503c4bd0-1aab-4e79-9043-8e89f9371a4d-SOFORT.png',
  STRIPE_CREDIT_CARD: THUMBNAILS_BASE_URL + '456863ab-2a66-4552-bfd7-828dcba8b15d-CARDS.png',
  STRIPE_DIRECT_DEBIT: THUMBNAILS_BASE_URL + '5a8aa19a-fd16-47df-8fdc-53e9d62af2d2-EC.png',
  WIRE_TRANSFER: THUMBNAILS_BASE_URL + 'aa48f41c-a41e-4572-a9b7-2362eb006ae0-EC.png',
  SWEDBANK: THUMBNAILS_BASE_URL + 'swedbank-136x136.png',
  APPLE_PAY: THUMBNAILS_BASE_URL + 'd18fa83a-91b1-4e77-980b-7c29913ce378-APPLE-PAY.png',
  GOOGLE_PAY: THUMBNAILS_BASE_URL + '9d918749-58f6-4ba6-849b-f4e93363158f-GOOGLE-PAY.png',
  OPENBANK: THUMBNAILS_BASE_URL + 'b25580cd-8dd7-488a-8d0f-49046d62c251-OPENBANK.png',
  IVY: THUMBNAILS_BASE_URL + '1106ba47-4228-412a-a70a-d2c40ce1c809-IVY.png',
  IDEAL: THUMBNAILS_BASE_URL + '398104c6-2923-44d8-9a2d-76d50a043561-IDEAL.png',
  BFS: THUMBNAILS_BASE_URL + '280c62f4-d6e3-464c-8b7d-1949df256a33-BFS.png',
  HSBC: THUMBNAILS_BASE_URL + 'ce8b26a1-eafd-4a77-af86-f511d012d410-HSBC.png',
  SANTANDER_INSTANT_AT: THUMBNAILS_BASE_URL + '7b00a1bc-8176-4d87-b39a-a932d2716b83-SANTANDER_INSTANT_AT.png',
};
const SANTANDER_INSTRUCTION_TEXT: string =
  'Simply enter the credentials of your merchant account with Santander, or apply for a new account at Santander Bank.';

const STRIPE_OPTIONS_CURRENCIES: string[] = [
  'AED',
  'AFN',
  'ALL',
  'AMD',
  'ANG',
  'AOA',
  'ARS',
  'AUD',
  'AWG',
  'AZN',
  'BAM',
  'BBD',
  'BDT',
  'BGN',
  'BIF',
  'BMD',
  'BND',
  'BOB',
  'BRL',
  'BSD',
  'BWP',
  'BZD',
  'CAD',
  'CDF',
  'CHF',
  'CLP',
  'CNY',
  'COP',
  'CRC',
  'CVE',
  'CZK',
  'DJF',
  'DKK',
  'DOP',
  'DZD',
  'EEK',
  'EGP',
  'ETB',
  'EUR',
  'FJD',
  'FKP',
  'GBP',
  'GEL',
  'GIP',
  'GMD',
  'GNF',
  'GTQ',
  'GYD',
  'HKD',
  'HNL',
  'HRK',
  'HTG',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'ISK',
  'JMD',
  'JPY',
  'KES',
  'KGS',
  'KHR',
  'KMF',
  'KRW',
  'KYD',
  'KZT',
  'LAK',
  'LBP',
  'LKR',
  'LRD',
  'LSL',
  'LTL',
  'LVL',
  'MAD',
  'MDL',
  'MGA',
  'MKD',
  'MNT',
  'MOP',
  'MRO',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MYR',
  'MZN',
  'NAD',
  'NGN',
  'NIO',
  'NOK',
  'NPR',
  'NZD',
  'PAB',
  'PEN',
  'PGK',
  'PHP',
  'PKR',
  'PLN',
  'PYG',
  'QAR',
  'RON',
  'RSD',
  'RUB',
  'RWF',
  'SAR',
  'SBD',
  'SCR',
  'SEK',
  'SGD',
  'SHP',
  'SLL',
  'SOS',
  'SRD',
  'STD',
  'SVC',
  'SZL',
  'THB',
  'TJS',
  'TOP',
  'TRY',
  'TTD',
  'TWD',
  'TZS',
  'UAH',
  'UGX',
  'USD',
  'UYU',
  'UZS',
  'VND',
  'VUV',
  'WST',
  'XAF',
  'XCD',
  'XOF',
  'XPF',
  'YER',
  'ZAR',
  'ZMW',
];
const STRIPE_OPTIONS_COUNTRIES: string[] = [
  'AU',
  'AT',
  'AZ',
  'AX',
  'AL',
  'DZ',
  'AS',
  'AI',
  'AO',
  'AD',
  'AQ',
  'AG',
  'AR',
  'AM',
  'AW',
  'AF',
  'BS',
  'BD',
  'BB',
  'BH',
  'BY',
  'BZ',
  'BE',
  'BJ',
  'BM',
  'BG',
  'BO',
  'BQ',
  'BA',
  'BW',
  'BR',
  'IO',
  'BN',
  'BF',
  'BI',
  'BT',
  'VU',
  'VA',
  'GB',
  'HU',
  'VE',
  'VG',
  'VI',
  'UM',
  'TL',
  'VN',
  'GA',
  'HT',
  'GY',
  'GM',
  'GH',
  'GP',
  'GT',
  'GN',
  'GW',
  'DE',
  'GG',
  'GI',
  'HN',
  'HK',
  'GD',
  'GL',
  'GR',
  'GE',
  'GU',
  'DK',
  'JE',
  'DJ',
  'DG',
  'DM',
  'DO',
  'EG',
  'ZM',
  'EH',
  'ZW',
  'IL',
  'IN',
  'ID',
  'JO',
  'IQ',
  'IR',
  'IE',
  'IS',
  'ES',
  'IT',
  'YE',
  'CV',
  'KZ',
  'KH',
  'CM',
  'CA',
  'IC',
  'QA',
  'KE',
  'CY',
  'KG',
  'KI',
  'CN',
  'KP',
  'CC',
  'CO',
  'KM',
  'CG',
  'CD',
  'XK',
  'CR',
  'CI',
  'CU',
  'KW',
  'CW',
  'LA',
  'LV',
  'LS',
  'LR',
  'LB',
  'LY',
  'LT',
  'LI',
  'LU',
  'MU',
  'MR',
  'MG',
  'YT',
  'MO',
  'MK',
  'MW',
  'MY',
  'ML',
  'MV',
  'MT',
  'MA',
  'MQ',
  'MH',
  'MX',
  'MZ',
  'MD',
  'MC',
  'MN',
  'MS',
  'MM',
  'NA',
  'NR',
  'NP',
  'NE',
  'NG',
  'NL',
  'NI',
  'NU',
  'NZ',
  'NC',
  'NO',
  'AC',
  'IM',
  'NF',
  'CX',
  'SH',
  'PN',
  'TC',
  'AE',
  'OM',
  'KY',
  'CK',
  'PK',
  'PW',
  'PS',
  'PA',
  'PG',
  'PY',
  'PE',
  'PL',
  'PT',
  'PR',
  'KR',
  'RE',
  'RU',
  'RW',
  'RO',
  'SV',
  'WS',
  'SM',
  'ST',
  'SA',
  'SZ',
  'MP',
  'SC',
  'BL',
  'MF',
  'PM',
  'SN',
  'VC',
  'KN',
  'LC',
  'RS',
  'EA',
  'SG',
  'SX',
  'SY',
  'SK',
  'SI',
  'US',
  'SB',
  'SO',
  'SD',
  'SR',
  'SL',
  'TJ',
  'TH',
  'TW',
  'TZ',
  'TG',
  'TK',
  'TO',
  'TT',
  'TA',
  'TV',
  'TN',
  'TM',
  'TR',
  'UG',
  'UZ',
  'UA',
  'WF',
  'UY',
  'FO',
  'FM',
  'FJ',
  'PH',
  'FI',
  'FK',
  'FR',
  'GF',
  'PF',
  'TF',
  'HR',
  'CF',
  'TD',
  'ME',
  'CZ',
  'CL',
  'CH',
  'SE',
  'SJ',
  'LK',
  'EC',
  'GQ',
  'ER',
  'EE',
  'ET',
  'GS',
  'ZA',
  'SS',
  'JM',
  'JP',
  'XA',
  'XB',
];

export const PaymentMethodsConfigs: PaymentMethodInterface[] = [
  {
    name: 'santander_factoring_de.name',
    amount_limits: {
      min: {
        EUR: 20,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'santander_factoring_de',
    description_offer: 'santander_factoring_de.description_offer',
    description_fee: 'santander_factoring_de.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DE',
    ],
    instruction_text: 'Just enter the keys of your Santander Invoice account. Or apply in order to open a new account.',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: true,
    share_bag_enabled: true,
  },
  {
    name: 'santander_pos_factoring_de.name',
    amount_limits: {
      min: {
        EUR: 20,
      },
      max: {
        EUR: 1500,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    payment_method: 'santander_pos_factoring_de',
    description_offer: 'santander_pos_factoring_de.description_offer',
    description_fee: 'santander_pos_factoring_de.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DE',
    ],
    instruction_text: 'payment_options.instructions.text.santander_pos_factoring_de',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: false,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: true,
  },
  {
    name: 'santander_installment_no.name',
    amount_limits: {
      min: {
        NOK: 1990,
      },
      max: {
        NOK: 80000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'santander_installment_no',
    description_offer: 'santander_installment_no.description_offer',
    description_fee: 'santander_installment_no.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DK',
      'DE',
      'FI',
      'NO',
      'AT',
      'SE',
      'CH',
      'ES',
    ],
    instruction_text: SANTANDER_INSTRUCTION_TEXT,
    related_country: 'NO',
    related_country_name: 'Norway',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'NOK',
      ],
      countries: [
        'NO',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: true,
  },
  {
    name: 'santander_pos_installment_no.name',
    amount_limits: {
      min: {
        NOK: 1990,
      },
      max: {
        NOK: 80000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'santander_pos_installment_no',
    description_offer: 'santander_pos_installment_no.description_offer',
    description_fee: 'santander_pos_installment_no.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DK',
      'DE',
      'FI',
      'NO',
      'AT',
      'SE',
      'CH',
      'ES',
    ],
    instruction_text: SANTANDER_INSTRUCTION_TEXT,
    related_country: 'NO',
    related_country_name: 'Norway',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'NOK',
      ],
      countries: [
        'NO',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: true,
  },
  {
    name: 'santander_invoice_no.name',
    amount_limits: {
      min: {
        NOK: 199,
      },
      max: {
        NOK: 35000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'santander_invoice_no',
    description_offer: 'santander_invoice_no.description_offer',
    description_fee: 'santander_invoice_no.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'NO',
    ],
    instruction_text: SANTANDER_INSTRUCTION_TEXT,
    related_country: 'NO',
    related_country_name: 'Norway',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'NOK',
      ],
      countries: [
        'NO',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'payex_creditcard.name',
    amount_limits: {
      min: {
        EUR: 0,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'payex_creditcard',
    description_offer: 'payex_creditcard.description_offer',
    description_fee: 'payex_creditcard.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'SE',
      'DK',
      'NO',
      'FI',
    ],
    instruction_text: '<p>Simply enter your account number and the encryption key of your ' +
      'PayEx account.</p>\n<p>PayEx Faktura(SE) service is available to Swedish end customers in Swedish ' +
      'currency-Swedish Krona (SEK)\n</p>\nIf you have any questions regarding your PayEx ' +
      'account please contact PayEx at 0498-20 29 45 (Mo-Fr 08:00-17:00).',
    related_country: 'SE',
    related_country_name: 'Sweden',
    thumbnail1: PaymentMethodsThumbnails.PAYEX,
    thumbnail2: PaymentMethodsThumbnails.PAYEX,
    options: {
      currencies: [
        'ALK',
        'ARM',
        'ARL',
        'BOL',
        'BAN',
        'BRZ',
        'BGO',
        'BGM',
        'CLE',
        'CNX',
        'ISJ',
        'ILR',
        'MKN',
        'MVP',
        'MDC',
        'MCF',
        'KRH',
        'KRO',
        'UYW',
        'VNN',
        'CHE',
        'CHW',
        'YUR',
        'ZWR',
        'ATS',
        'AOK',
        'AOR',
        'AON',
        'ADP',
        'ARA',
        'ARP',
        'AFA',
        'BYB',
        'BYR',
        'BEF',
        'BEC',
        'BEL',
        'BOV',
        'BOP',
        'BRR',
        'BRE',
        'BRB',
        'BRC',
        'BRN',
        'VEB',
        'DDM',
        'GHC',
        'GNS',
        'GRD',
        'GEK',
        'BUK',
        'BAD',
        'ZWD',
        'ZWL',
        'USN',
        'USS',
        'COU',
        'ZRZ',
        'PLZ',
        'ILP',
        'IEP',
        'ESP',
        'ESA',
        'ESB',
        'ITL',
        'YDD',
        'UAK',
        'ZMK',
        'CYP',
        'LUC',
        'LVL',
        'LVR',
        'BGL',
        'LTL',
        'LTT',
        'LSL',
        'LUF',
        'MGF',
        'MLF',
        'MTL',
        'MTP',
        'MAF',
        'MXV',
        'MXP',
        'MZE',
        'DEM',
        'NLG',
        'NIC',
        'ZRN',
        'PES',
        'PEI',
        'GWP',
        'PTE',
        'ECV',
        'RHD',
        'RUR',
        'SUR',
        'SVC',
        'SKK',
        'SIT',
        'ROL',
        'CSD',
        'AZM',
        'MZM',
        'SDP',
        'UGS',
        'SDD',
        'SRG',
        'TJR',
        'TPE',
        'TRL',
        'TMM',
        'UYI',
        'UYP',
        'CLF',
        'LUL',
        'FIM',
        'XFU',
        'XFO',
        'FRF',
        'HRD',
        'CSK',
        'XEU',
        'ECS',
        'GQE',
        'GWE',
        'EEK',
        'YUN',
        'YUM',
        'YUD',
        'ZAL',
        'AUD',
        'AZN',
        'ALL',
        'DZD',
        'AOA',
        'ARS',
        'AMD',
        'AWG',
        'AFN',
        'BSD',
        'BDT',
        'BBD',
        'BHD',
        'BZD',
        'BYN',
        'BMD',
        'BGN',
        'BOB',
        'BWP',
        'BRL',
        'GBP',
        'BND',
        'BIF',
        'BTN',
        'VUV',
        'HUF',
        'VES',
        'VEF',
        'XCD',
        'VND',
        'HTG',
        'GYD',
        'GMD',
        'GHS',
        'GTQ',
        'GNF',
        'GIP',
        'HNL',
        'HKD',
        'GEL',
        'DKK',
        'AED',
        'STN',
        'STD',
        'NAD',
        'KYD',
        'USD',
        'SBD',
        'TTD',
        'FJD',
        'DOP',
        'EUR',
        'EGP',
        'XRE',
        'ZMW',
        'INR',
        'IDR',
        'JOD',
        'IQD',
        'IRR',
        'ISK',
        'YER',
        'KZT',
        'KHR',
        'CAD',
        'QAR',
        'KES',
        'PGK',
        'KGS',
        'CNH',
        'CNY',
        'COP',
        'KMF',
        'BAM',
        'CDF',
        'CRC',
        'CUC',
        'CUP',
        'KWD',
        'LAK',
        'SLL',
        'LRD',
        'LBP',
        'LYD',
        'MUR',
        'MRU',
        'MRO',
        'MKD',
        'MWK',
        'MGA',
        'MYR',
        'MVR',
        'MAD',
        'MXN',
        'MZN',
        'MDL',
        'MNT',
        'MMK',
        'NPR',
        'NGN',
        'ANG',
        'NIO',
        'NZD',
        'ILS',
        'TWD',
        'TMT',
        'NOK',
        'OMR',
        'PKR',
        'PAB',
        'PYG',
        'MOP',
        'PEN',
        'PLN',
        'RUB',
        'RON',
        'WST',
        'SAR',
        'SZL',
        'KPW',
        'SCR',
        'RSD',
        'SGD',
        'SYP',
        'SOS',
        'SDG',
        'SRD',
        'TJS',
        'THB',
        'TZS',
        'TOP',
        'TND',
        'TRY',
        'UGX',
        'UZS',
        'UAH',
        'UYU',
        'PHP',
        'DJF',
        'XAF',
        'XOF',
        'RWF',
        'XPF',
        'FKP',
        'SHP',
        'HRK',
        'CZK',
        'CLP',
        'SEK',
        'CHF',
        'LKR',
        'ERN',
        'CVE',
        'ETB',
        'ZAR',
        'KRW',
        'SSP',
        'JMD',
        'JPY',
      ],
      countries: [
        'DK',
        'FI',
        'NO',
        'SE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'payex_faktura.name',
    amount_limits: {
      min: {
        SEK: 0,
        NOK: 0,
      },
      max: {
        SEK: 50000,
        NOK: 50000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'payex_faktura',
    description_offer: 'payex_faktura.description_offer',
    description_fee: 'payex_faktura.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'SE',
    ],
    instruction_text: '<p>Simply enter your account number and the encryption key of your PayEx ' +
      'account.</p>\n<p>PayEx Faktura(SE) service is available to Swedish end customers in Swedish ' +
      'currency-Swedish Krona (SEK)\n</p>\nIf you have any questions regarding your PayEx account ' +
      'please contact PayEx at 0498-20 29 45 (Mo-Fr 08:00-17:00).',
    related_country: 'SE',
    related_country_name: 'Sweden',
    thumbnail1: PaymentMethodsThumbnails.PAYEX,
    thumbnail2: PaymentMethodsThumbnails.PAYEX,
    options: {
      currencies: [
        'SEK',
        'NOK',
      ],
      countries: [
        'SE',
        'NO',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'santander_installment_se.name',
    amount_limits: {
      min: {
        SEK: 540,
      },
      max: {
        SEK: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'santander_installment_se',
    description_offer: 'santander_installment_se.description_offer',
    description_fee: 'santander_installment_se.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'SE',
      'DE',
      'DK',
      'NO',
      'ES',
      'AT',
      'FI',
      'CH',
    ],
    instruction_text: 'Instruction for Payment Method "Santander Ratenkauf Sweden"',
    related_country: 'SE',
    related_country_name: 'Sweden',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'SEK',
      ],
      countries: [
        'SE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: true,
  },
  {
    name: 'santander_pos_installment_se.name',
    amount_limits: {
      min: {
        SEK: 540,
      },
      max: {
        SEK: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    payment_method: 'santander_pos_installment_se',
    description_offer: 'santander_pos_installment_se.description_offer',
    description_fee: 'description_offer.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'SE',
    ],
    instruction_text: 'payment_options.instructions.text.santander_pos_installment_se',
    related_country: 'SE',
    related_country_name: 'Sweden',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'SEK',
      ],
      countries: [
        'SE',
      ],
    },
    shipping_address_allowed: false,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: true,
  },
  {
    name: 'santander_installment_dk.name',
    amount_limits: {
      min: {
        DKK: 1000,
      },
      max: {
        DKK: 350000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'santander_installment_dk',
    description_offer: 'santander_installment_dk.description_offer',
    description_fee: 'santander_installment_dk.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DK',
      'DE',
      'FI',
      'NO',
      'AT',
      'SE',
      'CH',
      'ES',
    ],
    instruction_text: 'Instruction for Payment Method "Santander Ratenkauf Denmark"',
    related_country: 'DK',
    related_country_name: 'Denmark',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'DKK',
      ],
      countries: [
        'DK',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: true,
  },
  {
    name: 'santander_pos_installment_dk.name',
    amount_limits: {
      min: {
        DKK: 1000,
      },
      max: {
        DKK: 350000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'santander_pos_installment_dk',
    description_offer: 'santander_pos_installment_dk.description_offer',
    description_fee: 'santander_pos_installment_dk.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DK',
      'DE',
      'FI',
      'NO',
      'AT',
      'SE',
      'CH',
      'ES',
    ],
    instruction_text: 'Instruction for Payment Method "Santander Ratenkauf Denmark"',
    related_country: 'DK',
    related_country_name: 'Denmark',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'DKK',
      ],
      countries: [
        'DK',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: true,
  },
  {
    name: 'santander_installment.name',
    amount_limits: {
      min: {
        EUR: 99,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'santander_installment',
    description_offer: 'santander_installment.description_offer',
    description_fee: 'santander_installment.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DK',
      'DE',
      'FI',
      'NO',
      'AT',
      'PT',
      'SE',
      'CH',
      'ES',
    ],
    instruction_text: SANTANDER_INSTRUCTION_TEXT,
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: false,
  },
  {
    name: 'santander_pos_installment.name',
    amount_limits: {
      min: {
        EUR: 99,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'santander_pos_installment',
    description_offer: 'santander_pos_installment.description_offer',
    description_fee: 'santander_pos_installment.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DE',
    ],
    instruction_text: SANTANDER_INSTRUCTION_TEXT,
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: false,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: false,
  },
  {
    name: 'santander_ccp_installment.name',
    amount_limits: {
      min: {
        EUR: 99,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'santander_ccp_installment',
    description_offer: 'santander_ccp_installment.description_offer',
    description_fee: 'description_offer.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DE',
    ],
    instruction_text: 'Instruction for Payment Method "Santander Installments Credit card Plus, Germany"',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: true,
    share_bag_enabled: true,
  },
  {
    name: 'santander_invoice_de.name',
    amount_limits: {
      min: {
        EUR: 5,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'santander_invoice_de',
    description_offer: 'santander_invoice_de.description_offer',
    description_fee: 'santander_invoice_de.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DE',
    ],
    instruction_text: 'Just enter the keys of your Santander Invoice account. Or apply in order to open a new account.',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'santander_pos_invoice_de.name',
    amount_limits: {
      min: {
        EUR: 5,
      },
      max: {
        EUR: 1500,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    payment_method: 'santander_pos_invoice_de',
    description_offer: 'santander_pos_invoice_de.description_offer',
    description_fee: 'santander_pos_invoice_de.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DE',
    ],
    instruction_text: 'payment_options.instructions.text.santander_pos_invoice_de',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: false,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'stripe.name',
    amount_limits: {
      min: {
        USD: 0.50,
        GBP: 0.30,
        EUR: 0.50,
        DKK: 2.50,
        NOK: 3.00,
        SEK: 3.00,
        CHF: 0.50,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0.25,
    variable_fee: 2.9,
    accept_fee: true,
    payment_method: 'stripe',
    description_offer: 'stripe.description_offer',
    description_fee: 'stripe.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [],
    instruction_text: 'Simply connect your Stripe and payever accounts, or create a new Stripe account.',
    thumbnail1: PaymentMethodsThumbnails.STRIPE_CREDIT_CARD,
    thumbnail2: PaymentMethodsThumbnails.STRIPE_CREDIT_CARD,
    options: {
      currencies: STRIPE_OPTIONS_CURRENCIES,
      countries: STRIPE_OPTIONS_COUNTRIES,
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
    organization_allowed: true,
  },
  {
    name: 'stripe_directdebit.name',
    amount_limits: {
      min: {
        EUR: 0,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0.25,
    variable_fee: 2.9,
    accept_fee: true,
    payment_method: 'stripe_directdebit',
    description_offer: 'stripe_directdebit.description_offer',
    description_fee: 'stripe_directdebit.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [],
    instruction_text: 'Simply connect your Stripe and payever accounts, or create a new Stripe account.',
    thumbnail1: PaymentMethodsThumbnails.STRIPE_DIRECT_DEBIT,
    thumbnail2: PaymentMethodsThumbnails.STRIPE_DIRECT_DEBIT,
    options: {
      currencies: ['EUR'],
      countries: [
        'AX',
        'AT',
        'PT',
        'BE',
        'BG',
        'ES',
        'IC',
        'HR',
        'CY',
        'CZ',
        'DK',
        'EE',
        'FI',
        'FR',
        'GF',
        'DE',
        'GI',
        'GR',
        'GP',
        'GG',
        'HU',
        'IS',
        'IE',
        'IM',
        'IT',
        'JE',
        'LV',
        'LI',
        'LT',
        'LU',
        'PT',
        'MT',
        'MQ',
        'YT',
        'MC',
        'NL',
        'NO',
        'PL',
        'PT',
        'RE',
        'RO',
        'BL',
        'MF',
        'PM',
        'SM',
        'SK',
        'SI',
        'ES',
        'SE',
        'CH',
        'GB',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
    organization_allowed: true,
  },
  {
    name: 'sofort.name',
    amount_limits: {
      min: {
        EUR: 0,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0.15,
    variable_fee: 0.8,
    accept_fee: true,
    payment_method: 'sofort',
    description_offer: 'sofort.description_offer',
    description_fee: 'sofort.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DE',
      'BE',
      'FR',
      'IT',
      'NL',
      'AT',
      'PL',
      'CH',
      'SK',
      'ES',
      'CZ',
      'HU',
      'GB',
    ],
    instruction_text: 'Create a new project and make sure that you use a "SOFORTGateway-Project" ' +
      'and choose "payever GmbH" as a Shop System. Enter the SOFORT Configuration-Key in your payever ' +
      'merchant account. Done!',
    thumbnail1: PaymentMethodsThumbnails.SOFORT,
    thumbnail2: PaymentMethodsThumbnails.SOFORT,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'BE',
        'NL',
        'CH',
        'HU',
        'DE',
        'AT',
        'SK',
        'GB',
        'IT',
        'PL',
        'ES',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'cash.name',
    amount_limits: {
      min: {
        EUR: 0,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'cash',
    description_offer: 'cash.description_offer',
    description_fee: 'cash.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DE',
      'FR',
      'LI',
      'LU',
      'NL',
      'AT',
      'PT',
      'CH',
      'ES',
      'GB',
    ],
    instruction_text: 'Complete your \naccount information accurately, ' +
      'so that your customers know where to send payments.',
    thumbnail1: PaymentMethodsThumbnails.WIRE_TRANSFER,
    thumbnail2: PaymentMethodsThumbnails.WIRE_TRANSFER,
    options: {
      currencies: [
        'AFN',
        'AFA',
        'ALL',
        'ALK',
        'DZD',
        'ADP',
        'AOA',
        'AOK',
        'AON',
        'AOR',
        'ARA',
        'ARS',
        'ARM',
        'ARP',
        'ARL',
        'AMD',
        'AWG',
        'AUD',
        'ATS',
        'AZN',
        'AZM',
        'BSD',
        'BHD',
        'BDT',
        'BBD',
        'BYN',
        'BYB',
        'BYR',
        'BEF',
        'BEC',
        'BEL',
        'BZD',
        'BMD',
        'BTN',
        'BOB',
        'BOL',
        'BOV',
        'BOP',
        'BAM',
        'BAD',
        'BAN',
        'BWP',
        'BRC',
        'BRZ',
        'BRE',
        'BRR',
        'BRN',
        'BRB',
        'BRL',
        'GBP',
        'BND',
        'BGL',
        'BGN',
        'BGO',
        'BGM',
        'BUK',
        'BIF',
        'XPF',
        'KHR',
        'CAD',
        'CVE',
        'KYD',
        'XAF',
        'CLE',
        'CLP',
        'CLF',
        'CNX',
        'CNY',
        'CNH',
        'COP',
        'COU',
        'KMF',
        'CDF',
        'CRC',
        'HRD',
        'HRK',
        'CUC',
        'CUP',
        'CYP',
        'CZK',
        'CSK',
        'DKK',
        'DJF',
        'DOP',
        'NLG',
        'XCD',
        'DDM',
        'ECS',
        'ECV',
        'EGP',
        'GQE',
        'ERN',
        'EEK',
        'ETB',
        'EUR',
        'XEU',
        'FKP',
        'FJD',
        'FIM',
        'FRF',
        'XFO',
        'XFU',
        'GMD',
        'GEK',
        'GEL',
        'DEM',
        'GHS',
        'GHC',
        'GIP',
        'GRD',
        'GTQ',
        'GWP',
        'GNF',
        'GNS',
        'GYD',
        'HTG',
        'HNL',
        'HKD',
        'HUF',
        'ISK',
        'ISJ',
        'INR',
        'IDR',
        'IRR',
        'IQD',
        'IEP',
        'ILS',
        'ILP',
        'ILR',
        'ITL',
        'JMD',
        'JPY',
        'JOD',
        'KZT',
        'KES',
        'KWD',
        'KGS',
        'LAK',
        'LVL',
        'LVR',
        'LBP',
        'LSL',
        'LRD',
        'LYD',
        'LTL',
        'LTT',
        'LUL',
        'LUC',
        'LUF',
        'MOP',
        'MKD',
        'MKN',
        'MGA',
        'MGF',
        'MWK',
        'MYR',
        'MVR',
        'MVP',
        'MLF',
        'MTL',
        'MTP',
        'MRU',
        'MRO',
        'MUR',
        'MXV',
        'MXN',
        'MXP',
        'MDC',
        'MDL',
        'MCF',
        'MNT',
        'MAD',
        'MAF',
        'MZE',
        'MZN',
        'MZM',
        'MMK',
        'NAD',
        'NPR',
        'ANG',
        'TWD',
        'NZD',
        'NIO',
        'NIC',
        'NGN',
        'KPW',
        'NOK',
        'OMR',
        'PKR',
        'PAB',
        'PGK',
        'PYG',
        'PEI',
        'PEN',
        'PES',
        'PHP',
        'PLN',
        'PLZ',
        'PTE',
        'GWE',
        'QAR',
        'XRE',
        'RHD',
        'RON',
        'ROL',
        'RUB',
        'RUR',
        'RWF',
        'SVC',
        'WST',
        'SAR',
        'RSD',
        'CSD',
        'SCR',
        'SLL',
        'SGD',
        'SKK',
        'SIT',
        'SBD',
        'SOS',
        'ZAR',
        'ZAL',
        'KRH',
        'KRW',
        'KRO',
        'SSP',
        'SUR',
        'ESP',
        'ESA',
        'ESB',
        'LKR',
        'SHP',
        'SDD',
        'SDG',
        'SDP',
        'SRD',
        'SRG',
        'SZL',
        'SEK',
        'CHF',
        'SYP',
        'STN',
        'STD',
        'TJR',
        'TJS',
        'TZS',
        'THB',
        'TPE',
        'TOP',
        'TTD',
        'TND',
        'TRY',
        'TRL',
        'TMT',
        'TMM',
        'USD',
        'USN',
        'USS',
        'UGX',
        'UGS',
        'UAH',
        'UAK',
        'AED',
        'UYW',
        'UYU',
        'UYP',
        'UYI',
        'UZS',
        'VUV',
        'VES',
        'VEB',
        'VEF',
        'VND',
        'VNN',
        'CHE',
        'CHW',
        'XOF',
        'YDD',
        'YER',
        'YUN',
        'YUD',
        'YUM',
        'YUR',
        'ZRN',
        'ZRZ',
        'ZMW',
        'ZMK',
        'ZWD',
        'ZWR',
        'ZWL',
      ],
      countries: [
        'AF',
        'AX',
        'AL',
        'DZ',
        'AS',
        'AD',
        'AO',
        'AI',
        'AQ',
        'AG',
        'AR',
        'AM',
        'AW',
        'AC',
        'AU',
        'AT',
        'AZ',
        'BS',
        'BH',
        'BD',
        'BB',
        'BY',
        'BE',
        'BZ',
        'BJ',
        'BM',
        'BT',
        'BO',
        'BA',
        'BW',
        'BR',
        'IO',
        'VG',
        'BN',
        'BG',
        'BF',
        'BI',
        'KH',
        'CM',
        'CA',
        'IC',
        'CV',
        'BQ',
        'KY',
        'CF',
        'EA',
        'TD',
        'CL',
        'CN',
        'CX',
        'CC',
        'CO',
        'KM',
        'CG',
        'CD',
        'CK',
        'CR',
        'CI',
        'HR',
        'CU',
        'CW',
        'CY',
        'CZ',
        'DK',
        'DG',
        'DJ',
        'DM',
        'DO',
        'EC',
        'EG',
        'SV',
        'GQ',
        'ER',
        'EE',
        'SZ',
        'ET',
        'FK',
        'FO',
        'FJ',
        'FI',
        'FR',
        'GF',
        'PF',
        'TF',
        'GA',
        'GM',
        'GE',
        'DE',
        'GH',
        'GI',
        'GR',
        'GL',
        'GD',
        'GP',
        'GU',
        'GT',
        'GG',
        'GN',
        'GW',
        'GY',
        'HT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IN',
        'ID',
        'IR',
        'IQ',
        'IE',
        'IM',
        'IL',
        'IT',
        'JM',
        'JP',
        'JE',
        'JO',
        'KZ',
        'KE',
        'KI',
        'XK',
        'KW',
        'KG',
        'LA',
        'LV',
        'LB',
        'LS',
        'LR',
        'LY',
        'LI',
        'LT',
        'LU',
        'MO',
        'MG',
        'MW',
        'MY',
        'MV',
        'ML',
        'MT',
        'MH',
        'MQ',
        'MR',
        'MU',
        'YT',
        'MX',
        'FM',
        'MD',
        'MC',
        'MN',
        'ME',
        'MS',
        'MA',
        'MZ',
        'MM',
        'NA',
        'NR',
        'NP',
        'NL',
        'NC',
        'NZ',
        'NI',
        'NE',
        'NG',
        'NU',
        'NF',
        'KP',
        'MK',
        'MP',
        'NO',
        'OM',
        'PK',
        'PW',
        'PS',
        'PA',
        'PG',
        'PY',
        'PE',
        'PH',
        'PN',
        'PL',
        'PT',
        'XA',
        'XB',
        'PR',
        'QA',
        'RE',
        'RO',
        'RU',
        'RW',
        'WS',
        'SM',
        'ST',
        'SA',
        'SN',
        'RS',
        'SC',
        'SL',
        'SG',
        'SX',
        'SK',
        'SI',
        'SB',
        'SO',
        'ZA',
        'GS',
        'KR',
        'SS',
        'ES',
        'LK',
        'BL',
        'SH',
        'KN',
        'LC',
        'MF',
        'PM',
        'VC',
        'SD',
        'SR',
        'SJ',
        'SE',
        'CH',
        'SY',
        'TW',
        'TJ',
        'TZ',
        'TH',
        'TL',
        'TG',
        'TK',
        'TO',
        'TT',
        'TA',
        'TN',
        'TR',
        'TM',
        'TC',
        'TV',
        'UM',
        'VI',
        'UG',
        'UA',
        'AE',
        'GB',
        'US',
        'UY',
        'UZ',
        'VU',
        'VA',
        'VE',
        'VN',
        'WF',
        'EH',
        'YE',
        'ZM',
        'ZW',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'paypal.name',
    amount_limits: {
      min: {
        EUR: 0.02,
        USD: 0.02,
        NOK: 0.10,
        SEK: 0.10,
        DKK: 0.10,
        GBP: 0.01,
      },
      max: {
        EUR: 10000,
      },
    },
    fixed_fee: 0.35,
    variable_fee: 1.9,
    accept_fee: true,
    payment_method: 'paypal',
    description_offer: 'paypal.description_offer',
    description_fee: 'paypal.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [],
    instruction_text: 'Simply connect your PayPal and payever accounts, or  create a new PayPal account.',
    thumbnail1: PaymentMethodsThumbnails.PAYPAL,
    thumbnail2: PaymentMethodsThumbnails.PAYPAL,
    options: {
      currencies: [
        'AUD',
        'CAD',
        'CZK',
        'DKK',
        'EUR',
        'GBP',
        'HKD',
        'HUF',
        'ILS',
        'JPY',
        'MYR',
        'MXN',
        'NOK',
        'NZD',
        'PHP',
        'PLN',
        'SGD',
        'SEK',
        'CHF',
        'TWD',
        'THB',
        'TRY',
        'USD',
      ],
      countries: [
        'AU',
        'AT',
        'AZ',
        'AX',
        'AL',
        'DZ',
        'AS',
        'AI',
        'AO',
        'AD',
        'AQ',
        'AG',
        'AR',
        'AM',
        'AW',
        'AF',
        'BS',
        'BD',
        'BB',
        'BH',
        'BY',
        'BZ',
        'BE',
        'BJ',
        'BM',
        'BG',
        'BO',
        'BQ',
        'BA',
        'BW',
        'BR',
        'IO',
        'BN',
        'BF',
        'BI',
        'BT',
        'VU',
        'VA',
        'GB',
        'HU',
        'VE',
        'VG',
        'VI',
        'UM',
        'TL',
        'VN',
        'GA',
        'HT',
        'GY',
        'GM',
        'GH',
        'GP',
        'GT',
        'GN',
        'GW',
        'DE',
        'GG',
        'GI',
        'HN',
        'HK',
        'GD',
        'GL',
        'GR',
        'GE',
        'GU',
        'DK',
        'JE',
        'DJ',
        'DG',
        'DM',
        'DO',
        'EZ',
        'EG',
        'ZM',
        'EH',
        'ZW',
        'IL',
        'IN',
        'ID',
        'JO',
        'IQ',
        'IR',
        'IE',
        'IS',
        'ES',
        'IT',
        'YE',
        'CV',
        'KZ',
        'KY',
        'KH',
        'CM',
        'CA',
        'IC',
        'QA',
        'KE',
        'CY',
        'KG',
        'KI',
        'CN',
        'KP',
        'CC',
        'CO',
        'KM',
        'CG',
        'CD',
        'XK',
        'CR',
        'CI',
        'CU',
        'KW',
        'CW',
        'LA',
        'LV',
        'LS',
        'LR',
        'LB',
        'LY',
        'LT',
        'LI',
        'LU',
        'MU',
        'MR',
        'MG',
        'YT',
        'MO',
        'MK',
        'MW',
        'MY',
        'ML',
        'MV',
        'MT',
        'MA',
        'MQ',
        'MH',
        'MX',
        'MZ',
        'MD',
        'MC',
        'MN',
        'MS',
        'MM',
        'NA',
        'NR',
        'NP',
        'NE',
        'NG',
        'NL',
        'NI',
        'NU',
        'NZ',
        'NC',
        'NO',
        'AC',
        'IM',
        'NF',
        'CX',
        'SH',
        'PN',
        'TC',
        'AE',
        'OM',
        'UN',
        'CK',
        'PK',
        'PW',
        'PS',
        'PA',
        'PG',
        'PY',
        'PE',
        'PL',
        'PT',
        'PR',
        'KR',
        'RE',
        'RU',
        'RW',
        'RO',
        'SV',
        'WS',
        'SM',
        'ST',
        'SA',
        'SZ',
        'MP',
        'SC',
        'BL',
        'MF',
        'PM',
        'SN',
        'VC',
        'KN',
        'LC',
        'RS',
        'EA',
        'SG',
        'SX',
        'SY',
        'SK',
        'SI',
        'US',
        'SB',
        'SO',
        'SD',
        'SR',
        'SL',
        'TJ',
        'TH',
        'TW',
        'TZ',
        'TG',
        'TK',
        'TO',
        'TT',
        'TA',
        'TV',
        'TN',
        'TM',
        'TR',
        'UG',
        'UZ',
        'UA',
        'WF',
        'UY',
        'FO',
        'FM',
        'FJ',
        'PH',
        'FI',
        'FK',
        'FR',
        'GF',
        'PF',
        'TF',
        'HR',
        'CF',
        'TD',
        'ME',
        'CZ',
        'CL',
        'CH',
        'SE',
        'SJ',
        'LK',
        'EC',
        'GQ',
        'ER',
        'EE',
        'ET',
        'GS',
        'ZA',
        'SS',
        'JM',
        'JP',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
    organization_allowed: true,
  },
  {
    name: 'instant_payment.name',
    amount_limits: {
      min: {
        EUR: 0,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    payment_method: 'instant_payment',
    description_offer: 'instant_payment.description_offer',
    description_fee: 'instant_payment.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [],
    instruction_text: 'payment_options.instructions.text.instant_payment',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'AFN',
        'AFA',
        'ALL',
        'ALK',
        'DZD',
        'ADP',
        'AOA',
        'AOK',
        'AON',
        'AOR',
        'ARA',
        'ARS',
        'ARM',
        'ARP',
        'ARL',
        'AMD',
        'AWG',
        'AUD',
        'ATS',
        'AZN',
        'AZM',
        'BSD',
        'BHD',
        'BDT',
        'BBD',
        'BYN',
        'BYB',
        'BYR',
        'BEF',
        'BEC',
        'BEL',
        'BZD',
        'BMD',
        'BTN',
        'BOB',
        'BOL',
        'BOV',
        'BOP',
        'BAM',
        'BAD',
        'BAN',
        'BWP',
        'BRC',
        'BRZ',
        'BRE',
        'BRR',
        'BRN',
        'BRB',
        'BRL',
        'GBP',
        'BND',
        'BGL',
        'BGN',
        'BGO',
        'BGM',
        'BUK',
        'BIF',
        'XPF',
        'KHR',
        'CAD',
        'CVE',
        'KYD',
        'XAF',
        'CLE',
        'CLP',
        'CLF',
        'CNX',
        'CNY',
        'CNH',
        'COP',
        'COU',
        'KMF',
        'CDF',
        'CRC',
        'HRD',
        'HRK',
        'CUC',
        'CUP',
        'CYP',
        'CZK',
        'CSK',
        'DKK',
        'DJF',
        'DOP',
        'NLG',
        'XCD',
        'DDM',
        'ECS',
        'ECV',
        'EGP',
        'GQE',
        'ERN',
        'EEK',
        'ETB',
        'EUR',
        'XEU',
        'FKP',
        'FJD',
        'FIM',
        'FRF',
        'XFO',
        'XFU',
        'GMD',
        'GEK',
        'GEL',
        'DEM',
        'GHS',
        'GHC',
        'GIP',
        'GRD',
        'GTQ',
        'GWP',
        'GNF',
        'GNS',
        'GYD',
        'HTG',
        'HNL',
        'HKD',
        'HUF',
        'ISK',
        'ISJ',
        'INR',
        'IDR',
        'IRR',
        'IQD',
        'IEP',
        'ILS',
        'ILP',
        'ILR',
        'ITL',
        'JMD',
        'JPY',
        'JOD',
        'KZT',
        'KES',
        'KWD',
        'KGS',
        'LAK',
        'LVL',
        'LVR',
        'LBP',
        'LSL',
        'LRD',
        'LYD',
        'LTL',
        'LTT',
        'LUL',
        'LUC',
        'LUF',
        'MOP',
        'MKD',
        'MKN',
        'MGA',
        'MGF',
        'MWK',
        'MYR',
        'MVR',
        'MVP',
        'MLF',
        'MTL',
        'MTP',
        'MRU',
        'MRO',
        'MUR',
        'MXV',
        'MXN',
        'MXP',
        'MDC',
        'MDL',
        'MCF',
        'MNT',
        'MAD',
        'MAF',
        'MZE',
        'MZN',
        'MZM',
        'MMK',
        'NAD',
        'NPR',
        'ANG',
        'TWD',
        'NZD',
        'NIO',
        'NIC',
        'NGN',
        'KPW',
        'NOK',
        'OMR',
        'PKR',
        'PAB',
        'PGK',
        'PYG',
        'PEI',
        'PEN',
        'PES',
        'PHP',
        'PLN',
        'PLZ',
        'PTE',
        'GWE',
        'QAR',
        'XRE',
        'RHD',
        'RON',
        'ROL',
        'RUB',
        'RUR',
        'RWF',
        'SVC',
        'WST',
        'STN',
        'STD',
        'SAR',
        'RSD',
        'CSD',
        'SCR',
        'SLL',
        'SGD',
        'SKK',
        'SIT',
        'SBD',
        'SOS',
        'ZAR',
        'ZAL',
        'KRH',
        'KRW',
        'KRO',
        'SSP',
        'SUR',
        'ESP',
        'ESA',
        'ESB',
        'LKR',
        'SHP',
        'SDD',
        'SDG',
        'SDP',
        'SRD',
        'SRG',
        'SZL',
        'SEK',
        'CHF',
        'SYP',
        'TJR',
        'TJS',
        'TZS',
        'THB',
        'TPE',
        'TOP',
        'TTD',
        'TND',
        'TRY',
        'TRL',
        'TMT',
        'TMM',
        'USD',
        'USN',
        'USS',
        'UGX',
        'UGS',
        'UAH',
        'UAK',
        'AED',
        'UYW',
        'UYU',
        'UYP',
        'UYI',
        'UZS',
        'VUV',
        'VES',
        'VEB',
        'VEF',
        'VND',
        'VNN',
        'CHE',
        'CHW',
        'XOF',
        'YDD',
        'YER',
        'YUN',
        'YUD',
        'YUM',
        'YUR',
        'ZRN',
        'ZRZ',
        'ZMW',
        'ZMK',
        'ZWD',
        'ZWR',
        'ZWL',
      ],
      countries: [
        'AF',
        'AX',
        'AL',
        'DZ',
        'AS',
        'AD',
        'AO',
        'AI',
        'AQ',
        'AG',
        'AR',
        'AM',
        'AW',
        'AU',
        'AT',
        'AZ',
        'BS',
        'BH',
        'BD',
        'BB',
        'BY',
        'BE',
        'BZ',
        'BJ',
        'BM',
        'BT',
        'BO',
        'BA',
        'BW',
        'BV',
        'BR',
        'IO',
        'VG',
        'BN',
        'BG',
        'BF',
        'BI',
        'KH',
        'CM',
        'CA',
        'CV',
        'BQ',
        'KY',
        'CF',
        'TD',
        'CL',
        'CN',
        'CX',
        'CC',
        'CO',
        'KM',
        'CG',
        'CD',
        'CK',
        'CR',
        'CI',
        'HR',
        'CU',
        'CW',
        'CY',
        'CZ',
        'DK',
        'DJ',
        'DM',
        'DO',
        'EC',
        'EG',
        'SV',
        'GQ',
        'ER',
        'EE',
        'SZ',
        'ET',
        'FK',
        'FO',
        'FJ',
        'FI',
        'FR',
        'GF',
        'PF',
        'TF',
        'GA',
        'GM',
        'GE',
        'DE',
        'GH',
        'GI',
        'GR',
        'GL',
        'GD',
        'GP',
        'GU',
        'GT',
        'GG',
        'GN',
        'GW',
        'GY',
        'HT',
        'HM',
        'HN',
        'HK',
        'HU',
        'IS',
        'IN',
        'ID',
        'IR',
        'IQ',
        'IE',
        'IM',
        'IL',
        'IT',
        'JM',
        'JP',
        'JE',
        'JO',
        'KZ',
        'KE',
        'KI',
        'KW',
        'KG',
        'LA',
        'LV',
        'LB',
        'LS',
        'LR',
        'LY',
        'LI',
        'LT',
        'LU',
        'MO',
        'MG',
        'MW',
        'MY',
        'MV',
        'ML',
        'MT',
        'MH',
        'MQ',
        'MR',
        'MU',
        'YT',
        'MX',
        'FM',
        'MD',
        'MC',
        'MN',
        'ME',
        'MS',
        'MA',
        'MZ',
        'MM',
        'NA',
        'NR',
        'NP',
        'NL',
        'NC',
        'NZ',
        'NI',
        'NE',
        'NG',
        'NU',
        'NF',
        'KP',
        'MK',
        'MP',
        'NO',
        'OM',
        'PK',
        'PW',
        'PS',
        'PA',
        'PG',
        'PY',
        'PE',
        'PH',
        'PN',
        'PL',
        'PT',
        'PR',
        'QA',
        'RE',
        'RO',
        'RU',
        'RW',
        'WS',
        'SM',
        'ST',
        'SA',
        'SN',
        'RS',
        'SC',
        'SL',
        'SG',
        'SX',
        'SK',
        'SI',
        'SB',
        'SO',
        'ZA',
        'GS',
        'KR',
        'SS',
        'ES',
        'LK',
        'BL',
        'SH',
        'KN',
        'LC',
        'MF',
        'PM',
        'VC',
        'SD',
        'SR',
        'SJ',
        'SE',
        'CH',
        'SY',
        'TW',
        'TJ',
        'TZ',
        'TH',
        'TL',
        'TG',
        'TK',
        'TO',
        'TT',
        'TN',
        'TR',
        'TM',
        'TC',
        'TV',
        'UM',
        'VI',
        'UG',
        'UA',
        'AE',
        'GB',
        'US',
        'UY',
        'UZ',
        'VU',
        'VA',
        'VE',
        'VN',
        'WF',
        'EH',
        'YE',
        'ZM',
        'ZW',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'swedbank_creditcard.name',
    amount_limits: {
      min: {
        EUR: 0,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'swedbank_creditcard',
    description_offer: 'swedbank_creditcard.description_offer',
    description_fee: 'swedbank_creditcard.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'SE',
      'DK',
      'NO',
      'FI',
    ],
    instruction_text: '<p></p>',
    related_country: 'SE',
    related_country_name: 'Sweden',
    thumbnail1: PaymentMethodsThumbnails.SWEDBANK,
    thumbnail2: PaymentMethodsThumbnails.SWEDBANK,
    options: {
      currencies: [
        'NOK', 'SEK', 'DKK', 'USD', 'EUR',
      ],
      countries: [
        'AU',
        'AT',
        'AZ',
        'AX',
        'AL',
        'DZ',
        'AS',
        'AI',
        'AO',
        'AD',
        'AQ',
        'AG',
        'AR',
        'AM',
        'AW',
        'AF',
        'BS',
        'BD',
        'BB',
        'BH',
        'BY',
        'BZ',
        'BE',
        'BJ',
        'BM',
        'BG',
        'BO',
        'BQ',
        'BA',
        'BW',
        'BR',
        'IO',
        'BN',
        'BF',
        'BI',
        'BT',
        'VU',
        'VA',
        'GB',
        'HU',
        'VE',
        'VG',
        'VI',
        'UM',
        'TL',
        'VN',
        'GA',
        'HT',
        'GY',
        'GM',
        'GH',
        'GP',
        'GT',
        'GN',
        'GW',
        'DE',
        'GG',
        'GI',
        'HN',
        'HK',
        'GD',
        'GL',
        'GR',
        'GE',
        'GU',
        'DK',
        'JE',
        'DJ',
        'DG',
        'DM',
        'DO',
        'EG',
        'ZM',
        'EH',
        'ZW',
        'IL',
        'IN',
        'ID',
        'JO',
        'IQ',
        'IR',
        'IE',
        'IS',
        'ES',
        'IT',
        'YE',
        'CV',
        'KZ',
        'KH',
        'CM',
        'CA',
        'IC',
        'QA',
        'KE',
        'CY',
        'KG',
        'KI',
        'CN',
        'KP',
        'CC',
        'CO',
        'KM',
        'CG',
        'CD',
        'XK',
        'CR',
        'CI',
        'CU',
        'KW',
        'CW',
        'LA',
        'LV',
        'LS',
        'LR',
        'LB',
        'LY',
        'LT',
        'LI',
        'LU',
        'MU',
        'MR',
        'MG',
        'YT',
        'MO',
        'MK',
        'MW',
        'MY',
        'ML',
        'MV',
        'MT',
        'MA',
        'MQ',
        'MH',
        'MX',
        'MZ',
        'MD',
        'MC',
        'MN',
        'MS',
        'MM',
        'NA',
        'NR',
        'NP',
        'NE',
        'NG',
        'NL',
        'NI',
        'NU',
        'NZ',
        'NC',
        'NO',
        'AC',
        'IM',
        'NF',
        'CX',
        'SH',
        'PN',
        'TC',
        'AE',
        'OM',
        'KY',
        'CK',
        'PK',
        'PW',
        'PS',
        'PA',
        'PG',
        'PY',
        'PE',
        'PL',
        'PT',
        'PR',
        'KR',
        'RE',
        'RU',
        'RW',
        'RO',
        'SV',
        'WS',
        'SM',
        'ST',
        'SA',
        'SZ',
        'MP',
        'SC',
        'BL',
        'MF',
        'PM',
        'SN',
        'VC',
        'KN',
        'LC',
        'RS',
        'EA',
        'SG',
        'SX',
        'SY',
        'SK',
        'SI',
        'US',
        'SB',
        'SO',
        'SD',
        'SR',
        'SL',
        'TJ',
        'TH',
        'TW',
        'TZ',
        'TG',
        'TK',
        'TO',
        'TT',
        'TA',
        'TV',
        'TN',
        'TM',
        'TR',
        'UG',
        'UZ',
        'UA',
        'WF',
        'UY',
        'FO',
        'FM',
        'FJ',
        'PH',
        'FI',
        'FK',
        'FR',
        'GF',
        'PF',
        'TF',
        'HR',
        'CF',
        'TD',
        'ME',
        'CZ',
        'CL',
        'CH',
        'SE',
        'SJ',
        'LK',
        'EC',
        'GQ',
        'ER',
        'EE',
        'ET',
        'GS',
        'ZA',
        'SS',
        'JM',
        'JP',
        'XA',
        'XB',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'swedbank_invoice.name',
    amount_limits: {
      min: {
        SEK: 0,
        NOK: 0,
      },
      max: {
        SEK: 50000,
        NOK: 50000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'swedbank_invoice',
    description_offer: 'swedbank_invoice.description_offer',
    description_fee: 'swedbank_invoice.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'SE',
      'NO',
      'FI',
    ],
    instruction_text: '<p></p>',
    related_country: 'SE',
    related_country_name: 'Sweden',
    thumbnail1: PaymentMethodsThumbnails.SWEDBANK,
    thumbnail2: PaymentMethodsThumbnails.SWEDBANK,
    options: {
      currencies: [
        'SEK',
        'NOK',
      ],
      countries: [
        'SE',
        'NO',
        'FI',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'santander_installment_nl.name',
    amount_limits: {
      min: {
        EUR: 99,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'santander_installment_nl',
    description_offer: 'santander_installment_nl.description_offer',
    description_fee: 'santander_installment_nl.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['NL'],
    instruction_text: '',
    related_country: 'NL',
    related_country_name: 'Netherlands',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'NL',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'santander_installment_at.name',
    amount_limits: {
      min: {
        EUR: 99,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'santander_installment_at',
    description_offer: 'santander_installment_at.description_offer',
    description_fee: 'santander_installment_at.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['AT'],
    instruction_text: '',
    related_country: 'AT',
    related_country_name: 'Austria',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'AT',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'apple_pay.name',
    amount_limits: {
      min: {
        USD: 0.50,
        GBP: 0.30,
        EUR: 0.50,
        DKK: 2.50,
        NOK: 3.00,
        SEK: 3.00,
        CHF: 0.50,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0.25,
    variable_fee: 2.9,
    accept_fee: true,
    payment_method: 'apple_pay',
    description_offer: 'apple_pay.description_offer',
    description_fee: 'apple_pay.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [],
    instruction_text: 'Simply connect your Apple Pay and payever accounts, or create a new Apple Pay account.',
    thumbnail1: PaymentMethodsThumbnails.APPLE_PAY,
    thumbnail2: PaymentMethodsThumbnails.APPLE_PAY,
    options: {
      currencies: STRIPE_OPTIONS_CURRENCIES,
      countries: STRIPE_OPTIONS_COUNTRIES,
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'google_pay.name',
    amount_limits: {
      min: {
        USD: 0.50,
        GBP: 0.30,
        EUR: 0.50,
        DKK: 2.50,
        NOK: 3.00,
        SEK: 3.00,
        CHF: 0.50,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0.25,
    variable_fee: 2.9,
    accept_fee: true,
    payment_method: 'google_pay',
    description_offer: 'google_pay.description_offer',
    description_fee: 'google_pay.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [],
    instruction_text: 'Simply connect your Google Pay and payever accounts, or create a new Google Pay account.',
    thumbnail1: PaymentMethodsThumbnails.GOOGLE_PAY,
    thumbnail2: PaymentMethodsThumbnails.GOOGLE_PAY,
    options: {
      currencies: STRIPE_OPTIONS_CURRENCIES,
      countries: STRIPE_OPTIONS_COUNTRIES,
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_bnpl.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_bnpl',
    description_offer: 'zinia_bnpl.description_offer',
    description_fee: 'zinia_bnpl.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['NL'],
    instruction_text: '',
    related_country: 'NL',
    related_country_name: 'Netherlands',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'NL',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'santander_installment_uk.name',
    amount_limits: {
      min: {
        GBP: 300,
      },
      max: {
        GBP: 15000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'santander_installment_uk',
    description_offer: 'santander_installment_uk.description_offer',
    description_fee: 'santander_installment_uk.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['GB'],
    instruction_text: '',
    related_country: 'GB',
    related_country_name: 'Great Britain',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'GBP',
      ],
      countries: [
        'GB',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: true,
  },
  {
    name: 'santander_pos_installment_uk.name',
    amount_limits: {
      min: {
        GBP: 300,
      },
      max: {
        GBP: 15000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'santander_pos_installment_uk',
    description_offer: 'santander_pos_installment_uk.description_offer',
    description_fee: 'santander_pos_installment_uk.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['GB'],
    instruction_text: '',
    related_country: 'GB',
    related_country_name: 'Great Britain',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'GBP',
      ],
      countries: [
        'GB',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: true,
  },
  {
    name: 'santander_installment_fi.name',
    amount_limits: {
      min: {
        EUR: 300,
      },
      max: {
        EUR: 40000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'santander_installment_fi',
    description_offer: 'santander_installment_fi.description_offer',
    description_fee: 'santander_installment_fi.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['FI'],
    instruction_text: '',
    related_country: 'FI',
    related_country_name: 'Finland',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'FI',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'santander_pos_installment_fi.name',
    amount_limits: {
      min: {
        EUR: 300,
      },
      max: {
        EUR: 40000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'santander_pos_installment_fi',
    description_offer: 'santander_pos_installment_fi.description_offer',
    description_fee: 'santander_pos_installment_fi.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['FI'],
    instruction_text: '',
    related_country: 'FI',
    related_country_name: 'Finland',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'FI',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_pos.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_pos',
    description_offer: 'zinia_pos.description_offer',
    description_fee: 'zinia_pos.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['NL'],
    instruction_text: '',
    related_country: 'NL',
    related_country_name: 'Netherlands',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'NL',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_installment.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_installment',
    description_offer: 'zinia_installment.description_offer',
    description_fee: 'zinia_installment.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['NL'],
    instruction_text: '',
    related_country: 'NL',
    related_country_name: 'Netherlands',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'NL',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_slice_three.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_slice_three',
    description_offer: 'zinia_slice_three.description_offer',
    description_fee: 'zinia_slice_three.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['NL'],
    instruction_text: '',
    related_country: 'NL',
    related_country_name: 'Netherlands',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'NL',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_pos_slice_three.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_pos_slice_three',
    description_offer: 'zinia_pos_slice_three.description_offer',
    description_fee: 'zinia_pos_slice_three.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['NL'],
    instruction_text: '',
    related_country: 'NL',
    related_country_name: 'Netherlands',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'NL',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_bnpl_de.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_bnpl_de',
    description_offer: 'zinia_bnpl_de.description_offer',
    description_fee: 'zinia_bnpl_de.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['DE'],
    instruction_text: '',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_pos_de.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_pos_de',
    description_offer: 'zinia_pos_de.description_offer',
    description_fee: 'zinia_pos_de.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['NL'],
    instruction_text: '',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_installment_de.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_installment_de',
    description_offer: 'zinia_installment_de.description_offer',
    description_fee: 'zinia_installment_de.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['DE'],
    instruction_text: '',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_pos_installment_de.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_pos_installment_de',
    description_offer: 'zinia_pos_installment_de.description_offer',
    description_fee: 'zinia_pos_installment_de.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['DE'],
    instruction_text: '',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_pos_installment.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_pos_installment',
    description_offer: 'zinia_pos_installment.description_offer',
    description_fee: 'zinia_pos_installment.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['NL'],
    instruction_text: '',
    related_country: 'NL',
    related_country_name: 'Netherlands',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'NL',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_slice_three_de.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_slice_three_de',
    description_offer: 'zinia_slice_three_de.description_offer',
    description_fee: 'zinia_slice_three_de.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['DE'],
    instruction_text: '',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'zinia_pos_slice_three_de.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 750,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'zinia_pos_slice_three_de',
    description_offer: 'zinia_pos_slice_three_de.description_offer',
    description_fee: 'zinia_pos_slice_three_de.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['DE'],
    instruction_text: '',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'ivy.name',
    amount_limits: {
      min: {
        USD: 0.50,
        GBP: 0.30,
        EUR: 0.50,
        DKK: 2.50,
        NOK: 3.00,
        SEK: 3.00,
        CHF: 0.50,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'ivy',
    description_offer: 'ivy.description_offer',
    description_fee: 'ivy.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [],
    instruction_text: '',
    thumbnail1: PaymentMethodsThumbnails.IVY,
    thumbnail2: PaymentMethodsThumbnails.IVY,
    options: {
      currencies: STRIPE_OPTIONS_CURRENCIES,
      countries: STRIPE_OPTIONS_COUNTRIES,
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },

  {
    name: 'santander_installment_be.name',
    amount_limits: {
      min: {
        EUR: 200,
      },
      max: {
        EUR: 50000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'santander_installment_be',
    description_offer: 'santander_installment_be.description_offer',
    description_fee: 'santander_installment_be.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: ['BE'],
    instruction_text: '',
    related_country: 'BE',
    related_country_name: 'Belgium',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'BE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },

  {
    name: 'ideal.name',
    amount_limits: {
      min: {
        EUR: 0.50,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0.29,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'ideal',
    description_offer: 'ideal.description_offer',
    description_fee: 'ideal.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [],
    instruction_text: '',
    thumbnail1: PaymentMethodsThumbnails.IDEAL,
    thumbnail2: PaymentMethodsThumbnails.IDEAL,
    options: {
      currencies: ['EUR'],
      countries: [
        'AU',
        'AT',
        'BE',
        'BG',
        'CA',
        'HR',
        'CY',
        'CZ',
        'DK',
        'EE',
        'FI',
        'FR',
        'DE',
        'GI',
        'GR',
        'HK',
        'HU',
        'IE',
        'IT',
        'JP',
        'LV',
        'LI',
        'LT',
        'LU',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NO',
        'PL',
        'PT',
        'RO',
        'SG',
        'SK',
        'SI',
        'ES',
        'SE',
        'CH',
        'GB',
        'US',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'vipps.name',
    amount_limits: {
      min: {
        NOK: 0,
      },
      max: {
        NOK: 50000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'vipps',
    description_offer: 'vipps.description_offer',
    description_fee: 'vipps.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'SE',
      'DK',
      'NO',
      'FI',
    ],
    instruction_text: '<p></p>',
    related_country: 'NO',
    related_country_name: 'Norway',
    thumbnail1: THUMBNAILS_BASE_URL + 'eeb936f9-3a67-41c7-819f-189b4d87e772-VIPPS.png',
    thumbnail2: THUMBNAILS_BASE_URL + 'eeb936f9-3a67-41c7-819f-189b4d87e772-VIPPS.png',
    options: {
      currencies: [
        'NOK',
      ],
      countries: [
        'NO',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'allianz_trade_b2b_bnpl.name',
    amount_limits: {
      min: {
        EUR: 99,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'allianz_trade_b2b_bnpl',
    description_offer: 'allianz.description_offer',
    description_fee: 'allianz.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: true,
    is_b2b_method: true,
    merchant_allowed_countries: [
      'DE',
    ],
    instruction_text: '<p></p>',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: THUMBNAILS_BASE_URL + '1688b07b-1ba0-4cb3-a0f8-c44ba09818aa-ALLIANZ.png',
    thumbnail2: THUMBNAILS_BASE_URL + '1688b07b-1ba0-4cb3-a0f8-c44ba09818aa-ALLIANZ.png',
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
    organization_allowed: true,
  },
  {
    name: 'swish.name',
    amount_limits: {
      min: {
        SEK: 0,
      },
      max: {
        SEK: 50000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'swish',
    description_offer: 'swish.description_offer',
    description_fee: 'swish.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'SE',
    ],
    instruction_text: '<p></p>',
    related_country: 'SE',
    related_country_name: 'Sweden',
    thumbnail1: THUMBNAILS_BASE_URL + 'eeb936f9-3a67-41c7-819f-189b4d87e772-SWISH.png',
    thumbnail2: THUMBNAILS_BASE_URL + 'eeb936f9-3a67-41c7-819f-189b4d87e772-SWISH.png',
    options: {
      currencies: [
        'SEK',
      ],
      countries: [
        'SE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'mobile_pay.name',
    amount_limits: {
      min: {
        DKK: 0,
      },
      max: {
        DKK: 50000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'mobile_pay',
    description_offer: 'mobile_pay.description_offer',
    description_fee: 'mobile_pay.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DK',
      'FI',
    ],
    instruction_text: '<p></p>',
    thumbnail1: THUMBNAILS_BASE_URL + '390a43d3-64be-48c3-b290-840979474269-MOBILE-PAY.png',
    thumbnail2: THUMBNAILS_BASE_URL + '390a43d3-64be-48c3-b290-840979474269-MOBILE-PAY.png',
    options: {
      currencies: [
        'DKK',
        'EUR',
      ],
      countries: [
        'DK',
        'FI',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'trustly.name',
    amount_limits: {
      min: {
        SEK: 0,
      },
      max: {
        SEK: 50000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'trustly',
    description_offer: 'trustly.description_offer',
    description_fee: 'trustly.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'SE',
      'FI',
    ],
    instruction_text: '<p></p>',
    thumbnail1: THUMBNAILS_BASE_URL + '18dfaf8e-8d68-4e57-a0e5-6ac12f6ba0a4-TRUSTLY.png',
    thumbnail2: THUMBNAILS_BASE_URL + '18dfaf8e-8d68-4e57-a0e5-6ac12f6ba0a4-TRUSTLY.png',
    options: {
      currencies: [
        'SEK',
        'EUR',
      ],
      countries: [
        'SE',
        'FI',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
  },
  {
    name: 'psa_b2b_bnpl.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 50000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'psa_b2b_bnpl',
    description_offer: 'psa_b2b_bnpl.description_offer',
    description_fee: 'psa_b2b_bnpl.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: true,
    is_b2b_method: true,
    merchant_allowed_countries: [
      'DE',
      'AT',
      'NL',
      'ES',
    ],
    instruction_text: '<p></p>',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
        'AT',
        'NL',
        'ES',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
    organization_allowed: true,
  },
  {
    name: 'zinia_lending_de.name',
    amount_limits: {
      min: {
        EUR: 99,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'zinia_lending_de',
    description_offer: 'zinia_lending_de.description_offer',
    description_fee: 'zinia_lending_de.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DE',
    ],
    instruction_text: '',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: false,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: false,
  },
  {
    name: 'zinia_pos_lending_de.name',
    amount_limits: {
      min: {
        EUR: 99,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: false,
    payment_method: 'zinia_pos_lending_de',
    description_offer: 'zinia_pos_lending_de.description_offer',
    description_fee: 'zinia_pos_lending_de.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: false,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DE',
    ],
    instruction_text: '',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.OPENBANK,
    thumbnail2: PaymentMethodsThumbnails.OPENBANK,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: false,
    shipping_address_equality: false,
    rates: true,
    share_bag_enabled: false,
  },
  {
    name: 'nets.name',
    amount_limits: {
      min: {
        EUR: 50,
      },
      max: {
        EUR: 50000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_issuer: 'aci',
    payment_method: 'nets',
    description_offer: 'nets.description_offer',
    description_fee: 'nets.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: true,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'DE',
    ],
    instruction_text: '<p></p>',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: THUMBNAILS_BASE_URL + 'a78410bd-612a-46d8-b102-dbc93d1660fb-NETS.png',
    thumbnail2: THUMBNAILS_BASE_URL + 'a78410bd-612a-46d8-b102-dbc93d1660fb-NETS.png',
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: false,
    rates: false,
    share_bag_enabled: true,
    organization_allowed: true,
  },
  {
    name: 'bfs_b2b_bnpl.name',
    amount_limits: {
      min: {
        EUR: 250,
      },
      max: {
        EUR: 100000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'bfs_b2b_bnpl',
    description_offer: 'bfs_b2b_bnpl.description_offer',
    description_fee: 'bfs_b2b_bnpl.description_fee',
    status: 'active',
    is_redirect_method: false,
    is_submit_method: true,
    is_b2b_method: true,
    merchant_allowed_countries: [
      'DE',
    ],
    instruction_text: '<p></p>',
    related_country: 'DE',
    related_country_name: 'Germany',
    thumbnail1: PaymentMethodsThumbnails.BFS,
    thumbnail2: PaymentMethodsThumbnails.BFS,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'DE',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
    organization_allowed: true,
  },
  {
    name: 'hsbc.name',
    amount_limits: {
      min: {
        EUR: 0,
      },
      max: {
        EUR: 1000000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'hsbc',
    description_offer: 'hsbc.description_offer',
    description_fee: 'hsbc.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: true,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'GB',
    ],
    instruction_text: '<p></p>',
    related_country: 'GB',
    related_country_name: 'United Kingdom',
    thumbnail1: PaymentMethodsThumbnails.HSBC,
    thumbnail2: PaymentMethodsThumbnails.HSBC,
    options: {
      currencies: [
        'GBP',
      ],
      countries: [
        'GB',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
    organization_allowed: true,
  },
  {
    name: 'santander_instant_at.name',
    amount_limits: {
      min: {
        EUR: 0,
      },
      max: {
        EUR: 1000000,
      },
    },
    fixed_fee: 0,
    variable_fee: 0,
    accept_fee: true,
    payment_method: 'santander_instant_at',
    description_offer: 'santander_instant_at.description_offer',
    description_fee: 'santander_instant_at.description_fee',
    status: 'active',
    is_redirect_method: true,
    is_submit_method: true,
    is_b2b_method: false,
    merchant_allowed_countries: [
      'AT',
    ],
    instruction_text: '<p></p>',
    related_country: 'AT',
    related_country_name: 'Austria',
    thumbnail1: PaymentMethodsThumbnails.SANTANDER_INSTANT_AT,
    thumbnail2: PaymentMethodsThumbnails.SANTANDER_INSTANT_AT,
    options: {
      currencies: [
        'EUR',
      ],
      countries: [
        'AT',
      ],
    },
    shipping_address_allowed: true,
    shipping_address_equality: true,
    rates: false,
    share_bag_enabled: true,
    organization_allowed: true,
  },
];
