export enum WidgetTypeEnum {
  All = 'all',
  Builder = 'builder',
  BuilderTranslate = 'builder-translate',
  Blog = 'blog',
  Checkout = 'checkout',
  Commerceos = 'commerceos',
  Connect = 'connect',
  Contacts = 'contacts',
  Coupons = 'coupons',
  Invoice = 'invoice',
  Marketing = 'marketing',
  Pos = 'pos',
  Products = 'products',
  Settings = 'settings',
  Shipping = 'shipping',
  Shop = 'shop',
  Site = 'site',
  Statistics = 'statistics',
  Studio = 'studio',
  Subscriptions = 'subscriptions',
  Transactions = 'transactions',
}
