export enum PaymentActionsEnum {
  Cancel = 'cancel',
  ShippingGoods = 'shipping_goods',
  Refund = 'refund',
  Return = 'return',
  Authorize = 'authorize',
  Capture = 'capture',
  Collection = 'collection',
  LatePayment = 'late_payment',
  Paid = 'paid',
  Remind = 'remind',
  Upload = 'upload',
  Edit = 'edit',
  EditDelivery = 'edit_delivery',
  EditReference = 'edit_reference',
  Verify = 'verify',
  SendSigningLink = 'send_signing_link',
  SigningLinkQr = 'signing_link_qr',
  MarkPaid = 'mark_paid',
  Claim = 'claim',
  ClaimUpload = 'claim_upload',
  ClaimCancel = 'claim_cancel',
  Settle = 'settle',
  Invoice = 'invoice',
}
