import { PaymentActionsEnum } from './payment-actions.enum';

export enum ThirdPartyPaymentActionsEnum {
  actionList = 'action-list',
  actionOptions = 'action-options',
  actionCancel = 'action-cancel',
  actionCapture = 'action-capture',
  actionEdit = 'action-edit',
  actionEditDelivery = 'action-edit-delivery',
  actionEditReference = 'action-edit-reference',
  actionRefund = 'action-refund',
  actionSendSigningLink = 'action-send-signing-link',
  actionSigningLinkQr = 'action-signing-link-qr',
  actionShippingGoods = 'action-shipping-goods',
  actionVerify = 'action-verify',
  actionUpload = 'action-upload',
  actionUpdateStatus = 'update-status',
  actionSettlementReport = 'settlement-report',
  actionMarkPaid = 'action-mark-paid',
  actionClaim = 'action-claim',
  actionClaimUpload = 'action-claim-upload',
  actionClaimCancel = 'action-claim-cancel',
  actionSettle = 'action-settle',
  actionInvoice = 'action-invoice',
}

export const TransactionActionsToThirdPartyActions: Map<string, string> = new Map<string, string>([
  [PaymentActionsEnum.Return, ThirdPartyPaymentActionsEnum.actionRefund],
  [PaymentActionsEnum.Refund, ThirdPartyPaymentActionsEnum.actionRefund],
  [PaymentActionsEnum.Authorize, ThirdPartyPaymentActionsEnum.actionCapture],
  [PaymentActionsEnum.Capture, ThirdPartyPaymentActionsEnum.actionCapture],
  [PaymentActionsEnum.ShippingGoods, ThirdPartyPaymentActionsEnum.actionShippingGoods],
  [PaymentActionsEnum.Cancel, ThirdPartyPaymentActionsEnum.actionCancel],
  [PaymentActionsEnum.Edit, ThirdPartyPaymentActionsEnum.actionEdit],
  [PaymentActionsEnum.EditDelivery, ThirdPartyPaymentActionsEnum.actionEditDelivery],
  [PaymentActionsEnum.EditReference, ThirdPartyPaymentActionsEnum.actionEditReference],
  [PaymentActionsEnum.Verify, ThirdPartyPaymentActionsEnum.actionVerify],
  [PaymentActionsEnum.Upload, ThirdPartyPaymentActionsEnum.actionUpload],
  [PaymentActionsEnum.SendSigningLink, ThirdPartyPaymentActionsEnum.actionSendSigningLink],
  [PaymentActionsEnum.SigningLinkQr, ThirdPartyPaymentActionsEnum.actionSigningLinkQr],
  [PaymentActionsEnum.MarkPaid, ThirdPartyPaymentActionsEnum.actionMarkPaid],
  [PaymentActionsEnum.Claim, ThirdPartyPaymentActionsEnum.actionClaim],
  [PaymentActionsEnum.ClaimUpload, ThirdPartyPaymentActionsEnum.actionClaimUpload],
  [PaymentActionsEnum.ClaimCancel, ThirdPartyPaymentActionsEnum.actionClaimCancel],
  [PaymentActionsEnum.Settle, ThirdPartyPaymentActionsEnum.actionSettle],
  [PaymentActionsEnum.Invoice, ThirdPartyPaymentActionsEnum.actionInvoice],
]);
