{{ $values := .Values }}
{{ $appName := printf "%s-job" $values.appName }}
{{ $deployEnv := .Values.deploy.env }}
apiVersion: batch/v1
kind: Job

metadata:
  name: {{ $appName}}
  namespace: {{ $values.namespace }}

  labels:
    app: {{ $appName }}
    tier: nodejs
    type: job

  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"

spec:
  backoffLimit: 1

  template:
    metadata:
      labels:
        app: {{ $appName }}
        tier: nodejs
        type: job

    spec:
      priorityClassName: {{ $values.priorityClass }}
      restartPolicy: Never

      imagePullSecrets:
        - name: {{ $values.image.pullSecretName }}

      containers:
        - name: node
          image: {{ $values.image.nodejs }}
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "/payever/deploy/job.sh" ]

          resources:
{{ if eq  $deployEnv "test" }}
{{ toYaml $values.resourcestest.job | indent 12 }}
{{ else if eq  $deployEnv "stage" }}
{{ toYaml $values.resourcesstage.job | indent 12 }}
{{ else }}
{{ toYaml $values.resourceslive.job | indent 12 }}
{{ end }}
          envFrom:
            - configMapRef:
                name: {{ $values.configMapRef }}
            - configMapRef:
                name: micro-url-map
            - secretRef:
                name: {{ $values.configMapRef }}

          env:
            - name: KUBERNETES_DEPLOYED
              value: "{{ now }}"
