import { TwoFactorTypeEnum, VerifyTypeEnum, PaymentMethodEnum } from '../../../../enum';
import { CreatePaymentAddressDto } from './create-payment-address.dto';
import { CreatePaymentSellerDto } from './create-payment-seller.dto';
import { CreatePaymentMessageDto } from './create-payment-message.dto';
import { CreatePaymentCompanyDto } from './create-payment-company.dto';
import { CreatePaymentShippingOptionDto } from './create-payment-shipping-option.dto';
import { ApiCallCartItemInterface } from '../../../../../common/interfaces';
import { CreatePaymentSplitDto } from './create-payment-split.dto';
import { CreatePaymentFooterUrlsDto } from './create-payment-footer-urls.dto';
import { CustomerTypeEnum } from '../../../../../common/enum';

export class CreatePaymentDto extends CreatePaymentAddressDto {
  public payment_issuer?: string;
  public payment_method: string;
  public channel: string;
  public channel_type?: string;
  public channel_source?: string;
  public channel_set_id: number;
  public amount: number;
  public fee: number;
  public cart: ApiCallCartItemInterface[];
  public order_id: string;
  public currency: string;
  public social_security_number?: string;
  public birthdate: Date;
  public phone: string;
  public email: string;
  public success_url: string;
  public pending_url: string;
  public failure_url: string;
  public cancel_url: string;
  public notice_url: string;
  public customer_redirect_url: string;
  public x_frame_host: string;
  public plugin_version?: string;
  public variant_id?: string;
  public allow_cart_step?: boolean;
  public use_inventory?: boolean;
  public expires_at?: Date;
  public extra?: any;
  public client_id?: string;
  public shipping_address?: CreatePaymentAddressDto;
  public locale?: string;
  public verify_type?: VerifyTypeEnum;
  public verify_two_factor?: TwoFactorTypeEnum;
  public seller?: CreatePaymentSellerDto;
  public payment_data?: any;
  public reusable?: boolean;
  public link_message?: CreatePaymentMessageDto;
  public skip_handle_payment_fee?: boolean;
  public client_ip?: string;
  public user_agent?: string;

  public reference_extra?: string;
  public purchase_country?: string;
  public customer_type?: CustomerTypeEnum;
  public customer_gender?: string;
  public company?: CreatePaymentCompanyDto;
  public shipping_option?: CreatePaymentShippingOptionDto;
  public splits?: CreatePaymentSplitDto[];
  public allow_separate_shipping_address?: boolean;
  public allow_customer_types?: CustomerTypeEnum[];
  public allow_payment_methods?: PaymentMethodEnum[];
  public allow_billing_step?: boolean;
  public allow_shipping_step?: boolean;
  public use_styles?: boolean;
  public use_default_variant?: boolean;
  public use_iframe?: boolean;
  public salutation_mandatory?: boolean;
  public phone_mandatory?: boolean;
  public birthdate_mandatory?: boolean;
  public test_mode?: boolean;
  public api_version?: string;
  public order_ref?: string;
  public original_cart?: any;
  public down_payment?: number;
  public footer_urls?: CreatePaymentFooterUrlsDto;
  public hide_logo?: boolean;
  public hide_imprint?: boolean;
  public auto_capture_enabled?: boolean;
  public auto_capture_date?: Date;
  public disable_validation?: boolean;

  public privacy?: boolean;

  public payment_link_id?: string;
}
