export enum PaymentActionsEnum {
  Cancel = 'cancel',
  ShippingGoods = 'shipping_goods',
  Refund = 'refund',
  Return = 'return',
  Authorize = 'authorize',
  Capture = 'capture',
  ChangeAmount = 'change_amount',
  Collection = 'collection',
  LatePayment = 'late_payment',
  Paid = 'paid',
  Remind = 'remind',
  Upload = 'upload',
  Edit = 'edit',
  EditDelivery = 'edit_delivery',
  EditReference = 'edit_reference',
  Verify = 'verify',
  SendSigningLink = 'send_signing_link',
}
