POST http://localhost:3000/products
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  updateOption(id: "20b3ffe2-0d5f-4269-b54f-627c57cecbd9", data: { name: "opt2", value: "val2" }) {
    _id
    name
    value
  }
}
