export enum StatusesEnum {
  JustLooking = 'BUSINESS_STATUS_JUST_LOOKING',
  HaveIdea = 'BUSINESS_STATUS_HAVE_IDEA',
  TurnExisting = 'BUSINESS_STATUS_TURN_EXISTING',
  GrowingBusiness = 'BUSINESS_STATUS_GROWING_BUSINESS',
  ReplaceBusiness = 'BUSINESS_STATUS_REPLACE_BUSINESS',
}
