Feature: Section API

  Scenario: Get section
    Given I authenticate as a user with the following data:
      """
      {
        "email": "email@test.com",
        "roles": [
          {
            "name": "merchant",
            "permissions": []
          }
        ]
      }
      """
    Given I use DB fixture "checkout/section/existing"
    When I send a GET request to "/api/sections"
    Then print last response
    Then the response status code should be 200
    And the response should contain json:
      """
      [
        {
          "_id":"26cc1780-6dbd-4085-8002-b11056f21a35",
          "code":"send_to_device",
          "order":-1,
          "fixed":false,
          "defaultEnabled":false,
          "excluded_channels":[],
          "subsections":[
            {
              "rules":[],
              "_id":"d403d4c3-c447-4aab-a8c7-c7f184a8e77f",
              "code":"checkout-send-to-device"
            }
          ],
          "__v":0
        },
        {
          "_id":"87695a9d-ab32-4fa5-b958-cf637eb6340a",
          "code":"order",
          "order":0,
          "fixed":true,
          "defaultEnabled":true,
          "excluded_channels":[
            "finance_express",
            "api",
            "dandomain",
            "jtl",
            "magento",
            "oxid",
            "plentymarkets",
            "presta",
            "shopify",
            "opencart",
            "shopware_cloud",
            "oro_commerce",
            "shopware",
            "woo_commerce",
            "xt_commerce",
            "commercetools",
            "ccvshop",
            "connectin",
            "smartstore"
          ],
          "subsections":[
            {
              "rules":[
                {
                  "_id":"261e569a-7d98-444f-87b6-28cb21cf191e",
                  "type":"flow_property",
                  "property":"cart",
                  "operator":"isNotEmpty"
                }
              ],
              "_id":"9a6ee51f-30d2-44f9-a880-3d0d4af5727b",
              "code":"cart"
            },
            {
              "rules":[
                {
                  "_id":"3e809d11-0a15-4362-8c46-490e4520d428",
                  "type":"flow_property",
                  "property":"cart",
                  "operator":"isEmpty"
                }
              ],
              "_id":"91cad3f0-d48a-4d37-a46f-5bfbacf36ad0",
              "code":"amount_reference"
            }
          ],
          "__v":0
        },
        {
          "_id":"939dfaa7-908e-478a-bc68-1018da075eb6",
          "code":"user",
          "order":1,
          "fixed":false,
          "defaultEnabled":true,
          "excluded_channels":[
            "api",
            "dandomain",
            "jtl",
            "magento",
            "oxid",
            "plentymarkets",
            "presta",
            "shopify",
            "opencart",
            "shopware_cloud",
            "oro_commerce",
            "shopware",
            "woo_commerce",
            "xt_commerce",
            "commercetools",
            "ccvshop",
            "connectin",
            "smartstore"
          ],
          "subsections":[
            {
              "rules":[],
              "_id":"9869c0b9-5c9f-47a4-b31c-1fc93c1cadaf",
              "code":"checkout-main-user"
            }
          ],
          "__v":0
        },
        {
          "_id":"67b70735-bd5c-4894-b17f-1e9e8a7a1515",
          "code":"address",
          "order":2,
          "fixed":false,
          "defaultEnabled":true,
          "excluded_channels":[
            "api",
            "dandomain",
            "jtl",
            "magento",
            "oxid",
            "plentymarkets",
            "presta",
            "shopify",
            "opencart",
            "shopware_cloud",
            "oro_commerce",
            "shopware",
            "woo_commerce",
            "xt_commerce",
            "commercetools",
            "ccvshop",
            "connectin",
            "smartstore"
          ],
          "subsections":[
            {
              "rules":[],
              "_id":"ee04ca85-9885-4736-b468-f48691c95051",
              "code":"checkout-main-address"
            }
          ],
          "__v":0
        },
        {
          "_id":"e16ebb03-20f2-4517-a97b-41de5086f97a",
          "code":"shipping",
          "order":3,
          "fixed":false,
          "defaultEnabled":false,
          "excluded_channels":[],
          "subsections":[
            {
              "rules":[],
              "_id":"c5164dbc-fd07-4984-a43d-a02e31ea1aa1",
              "code":"checkout-main-shipping"
            }
          ],
          "__v":0
        },
        {
          "_id":"aaa84f89-e4b9-47f9-80f9-decf697294ea",
          "code":"choosePayment",
          "order":4,
          "fixed":true,
          "defaultEnabled":true,
          "excluded_channels":[],
          "subsections":[
            {
              "rules":[],
              "_id":"a25f79e0-7aa3-4b01-bdaa-473a24806feb",
              "code":"checkout-main-choose-payment"
            }
          ],
          "__v":0
        },
        {
          "_id":"dc558619-fa10-4baf-978b-b2c33b1deb82",
          "code":"payment",
          "order":5,
          "fixed":true,
          "defaultEnabled":true,
          "excluded_channels":[],
          "subsections":[
            {
              "rules":[],
              "_id":"85104cf5-2b71-441b-a47b-19c74e25ae2d",
              "code":"checkout-main-payment"
            }
          ],
          "__v":0
        }
      ]
      """

  Scenario: Get section, endpoint permission
    Given I am not authenticated
    When I send a GET request to "/api/sections"
    Then print last response
    Then the response status code should be 403
